### ISSUE TITLE
Wrap-up Keycloak 18 release

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#11002]
### Description

Remaining:
* [x] [Quarkus dist remaining tasks](https://github.com/keycloak/keycloak/issues?q=is%3Aissue+milestone%3A18.0.0+is%3Aopen+label%3Aarea%2Fdist%2Fquarkus)
* [x] [New Operator preview readiness](https://github.com/keycloak/keycloak/issues?q=is%3Aissue+milestone%3A18.0.0+is%3Aopen+label%3Aarea%2Foperator+)
* [x] [New Admin Console preview readiness](https://github.com/keycloak/keycloak/issues/11000)
* [x] [Upgrade to WildFly 26.1](https://github.com/keycloak/keycloak/issues/10999)
* [x] [Nashorn performance degradation on JDK 11 ](https://github.com/keycloak/keycloak/issues/11005)
* [x] Client secret rotation - https://github.com/keycloak/keycloak-documentation/pull/1449
* [x] [Configurable session limits](https://github.com/keycloak/keycloak/issues/10077) 
    * [x] [Configurable session limits documentation](https://github.com/keycloak/keycloak-documentation/issues/1450)
* [x] Support for parameterized client scopes
* [ ] Remove ability to upload JavaScript through Admin APIs https://github.com/keycloak/keycloak/issues/9865

Release notes:
* [x] Review
* [x] [OIDC RP-initiated logout](https://github.com/keycloak/keycloak/issues/10885)
* [x] [GitHub Enterprise server brokering](https://github.com/keycloak/keycloak/pull/7021)
* [x] New Operator preview
* [x] New Admin Console preview
* [x] [Recovery codes](https://github.com/keycloak/keycloak/issues/9540)
* [x] Step-up authentication
* [x] Client secret rotation
* [x] [Configurable session limits](https://github.com/keycloak/keycloak/issues/10077)
* [x] [WebAuthN idless](https://github.com/keycloak/keycloak/issues/10832)
* [x] Quarkus dist improvements
* [x] https://github.com/keycloak/keycloak/issues/10300?
* [x] https://github.com/keycloak/keycloak/issues/10885
* [x] https://github.com/keycloak/keycloak/pull/10748

Migration guide:
* [ ] Review
* [ ] Quarkus dist changes
* [ ] RP-initiated logout

Postponed:
* [ ] Java 17 support
* [ ] Persisted consents for parameterized client scopes

Issues:

* [Open](https://github.com/keycloak/keycloak/issues?q=is%3Aissue+milestone%3A18.0.0+is%3Aopen)
    * [Excluding Quarkus/Operator](https://github.com/keycloak/keycloak/issues?q=is%3Aissue+milestone%3A18.0.0+is%3Aopen+-label%3Aarea%2Fdist%2Fquarkus+-label%3Aarea%2Foperator)

**Comment by Submoon** [comment]
Hi! Is there some sort of revised timeline for when we can hope to have a stable version of KC 18? That could be useful to know for a project I'm working on!

**Comment by hypery2k** [comment]
@heddn any chance for a nearby v18 release?

**Comment by iposmashnyi** [comment]
@pedroigor maybe you can point out when is the new version going to be released?

**Comment by luneo7** [comment]
@stianst @pedroigor Github Actions to release keycloak container (https://github.com/keycloak/keycloak/actions/runs/2197864203) && operator (https://github.com/keycloak/keycloak/actions/runs/2197864206) failed =/
