### ISSUE TITLE
Hardened Content Security Policy (CSP)

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16277]
### Description

The default Content Security Policy (CSP) used by Keycloak is not locked down enough, and should be improved as it adds a lot of additional protection against XSS attacks.

We need to investigate what would be the best header. In addition it will need to be dynamic/smart as different parts of Keycloak requires different CSP headers.

In addition there may be a need to for users to be able to configure some aspects of the CSP header for some situations. Currently this is done by completely overriding the header, but this is not great as it results in a less secure CSP header as the same header is applied to everything Keycloak does.

### Details

See #16759, #15874, #14078, #9553

### Tasks

- [ ] #21728
- [ ] https://github.com/keycloak/keycloak/issues/32901
- [ ] #29782
- [ ] #32079
- [ ] #32078
- [ ] https://github.com/keycloak/keycloak/issues/32123
- [ ] https://github.com/keycloak/keycloak/issues/37430
- [ ] https://github.com/keycloak/keycloak/issues/40589
- [ ] https://github.com/keycloak/keycloak/issues/42264
- [ ] #43023

**Comment by ChristianCiach** [comment]
Some professional security advisers asked us to set the CSP header to `default-src 'self'; frame-ancestors 'self'; object-src 'none'`, but this is currently not possible. These are the issues I've encountered:

* The account console uses inline-script, so I had to add `script-src 'self' 'unsafe-inline';`.
* The admin console uses inline-style in addition to inline-script, so I had to add `style-src 'self' 'unsafe-inline';`.
* The user login page neither uses inline-script nor inline-style, but when entering wrong credentials, a little SVG icon is disabled by using inlined base64 `data:` scheme, so I had to add `img-src 'self' data:;`.

This is true for Keycloak 20.0.1 when using the default theme. This list is surely not complete. I just wanted to contribute my own findings to this issue.

So, my completely CSP header currently looks like this:
```
frame-ancestors 'self'; default-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:;
```

Especially the `unsafe-inline` ones are undesirable, but the embedded images (using the `data:` scheme) should also be extracted as proper image files if possible.

**Comment by jonkoops** [comment]
> The admin console uses inline-style in addition to inline-script, so I had to add style-src 'self' 'unsafe-inline';.

Where is this script located? The only one I am aware of is of a type that should not be executable.

**Comment by ChristianCiach** [comment]
@jonkoops I am not sure if this is what you are asking, but when I open the admin console at `https://my-keycloak.local/auth/admin/master/console/#/`, this is the html source:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <base href="/auth/resources/avqhv/admin/keycloak.v2/" />
    <link rel="icon" type="image/svg+xml" href="/auth/resources/avqhv/admin/keycloak.v2/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Web site to manage keycloak" />
    <title>Keycloak Administration Console</title>
    <style>
      body {
        margin: 0;
      }

      body, #app {
        height: 100%;
      }

      .container {
        padding: 0;
        margin: 0;
        width: 100%;
      }

      .keycloak__loading-container {
        height: 100vh;
        width: 100%;
        background-color: #f0f0f0;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        margin: 0;
      }

      #loading-text {
        z-index: 1000;
        font-size: 20px;
        font-weight: 600;
        padding-top: 32px;
      }
    </style>
    <script type="module" crossorigin src="/auth/resources/avqhv/admin/keycloak.v2/assets/index.0cb2e516.js"></script>
    <link rel="stylesheet" href="/auth/resources/avqhv/admin/keycloak.v2/assets/index.e2193254.css">
  

  </head>
	

  <body>
    <div id="app">
      <div class="container">
        <div class="keycloak__loading-container">
          <span class="pf-c-spinner pf-m-xl" role="progressbar" aria-valuetext="Loading...">
            <span class="pf-c-spinner__clipper"></span>
            <span class="pf-c-spinner__lead-ball"></span>
            <span class="pf-c-spinner__tail-ball"></span>
          </span>
          <div>
            <p id="loading-text">Loading the admin console</p>
          </div>
        </div>
      </div>
    </div>

    <noscript>You need to enable JavaScript to run this app.</noscript>
    
  

  <script id="environment" type="application/json">
    {
      "loginRealm": "master",
      "authServerUrl": "https://my-keycloak.local/auth",
      "authUrl": "https://my-keycloak.local/auth",
      "consoleBaseUrl": "/auth/admin/master/console/",
      "resourceUrl": "/auth/resources/avqhv/admin/keycloak.v2",
      "masterRealm": "master",
      "resourceVersion": "avqhv",
      "commitHash": "8d2c75c5b530fa67e76b77c860320d8ed5e3d099",
      "isRunningAsTheme": true
    }
  </script>
</body>


</html>

```

As you can see, the whole page is essentially a single `div`, the rest being inline-style and inline-script. If I forbid the loading of the script by omitting `script-src 'unsafe-inline'`, then the admin console won't load (showing a loading throbber forever).

**Comment by jonkoops** [comment]
@ChristianCiach the only script I am seeing here is non-executable. `script-src 'unsafe-inline'` blocks that as well?

**Comment by ChristianCiach** [comment]
@jonkoops It looks like I was wrong. Sorry about that! Chrome actually complains about these to things:

At `https://my-keycloak.local/auth/admin/master/console/` `:10`:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Nx73PRBbtDNJn7vKyE+HPicspzFRfNSmMMyBYXQtT9E='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`
```

At `https://my-keycloak.local/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html` `:7`:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-ojdN+QBxqZx2irtk+NdVEpnJ80rZvUusqKdiGBaJ2wY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

`step1.html` seems to be an iframe, with this inline script:
```html
<script>
      if ("hasStorageAccess" in document) {
        checkStorageAccess();
      } else {
        placeTestCookie();
      }

      function checkStorageAccess() {
        document.hasStorageAccess().then(function (hasAccess) {
          window.parent.postMessage(
            hasAccess ? "supported" : "unsupported",
            "*"
          );
        });
      }

      function placeTestCookie() {
        document.cookie =
          "KEYCLOAK_3P_COOKIE_SAMESITE=supported; Max-Age=60; SameSite=None; Secure";
        document.cookie = "KEYCLOAK_3P_COOKIE=supported; Max-Age=60";
        window.location = "step2.html";
      }
    </script>
```

This is pretty much everything that I can see. I am not a JavaScript developer and my skills using the browser console are very limited.

**Comment by jonkoops** [comment]
Thanks for verifying that, I think we can certainly look into adding a nonce or hash for these ones. Question is what the right direction is for these (see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)).

**Comment by ChristianCiach** [comment]
Using hashes or nonces would make it very tough to continue to allow setting custom CSP header as part of the realm settings. The only way I could think of to make this work would be some kind of variable that we could use inside the custom CSP header, like `script-src 'self' 'nonce-{{ SCRIPT_NONCE }}';`. 

If course, the nonce must be unique for every request, since it would be useless otherwise. 

At this point it may be easier to "just" move all inline scripts to external files, but that may be easier said than done if the scripts are dynamically generated.

**Comment by jonkoops** [comment]
> At this point it may be easier to "just" move all inline scripts to external files

I mean yes, if it does have a security benefit. For example, that script in the iframe is already in a performance critical section and is not dynamically generated - so an unrealistic attack vector.

**Comment by gracegyu** [comment]
I'm having the same problem too. has it been resolved?

Adding "style-src 'self' 'unsafe-inline';" to Content-Security-Policy doesn't work.
```
Refused to frame 'http://localhost:8080/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

**Comment by epuronta** [comment]
I'm interested in this as well. The issue came up with an automated security scanner, which (appropriately) flagged the permissive CSP policies. Applying more restrictive policies causes several issues with the default templates, making it impractical for us.

On a related topic, it seems that customizing the CSP headers on the welcome page is impossible as all the admin-configurable policies apply on a realm level. The common welcome page is obviously not part of any single realm. This is problematic for more primitive scanners that only scan the domain root = welcome page.

**Comment by olbusat** [comment]
Faced with the same problem. Subscribing for comments :)

**Comment by m4rc77** [comment]
FYI: **theme/keycloak.v2 requires 'unsafe-eval' in Content-Security-Policy (CSP)** : https://github.com/keycloak/keycloak/issues/24802

**Comment by shubhit7** [comment]
> I'm having the same problem too. has it been resolved?
> 
> Adding "style-src 'self' 'unsafe-inline';" to Content-Security-Policy doesn't work.
> 
> ```
> Refused to frame 'http://localhost:8080/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
> ```

I was facing similar error on browser console in my angular application. This was only happening in case of check-sso init options with silent redirect.
Adding `http://localhost:4200/*` (default url for angular apps) in **Valid redirect URIs** in keycloak client fixed the issue.

**Comment by zc-devs** [comment]
On `23.0.6` version I had to develop CSP below in Traefik:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  routes:
    - kind: Rule
      match: Host(`keycloak.example.org`) && PathPrefix(`/admin`)
      priority: 3
      middlewares:
        - name: keycloak-admin-headers
    - kind: Rule
      match: Host(`keycloak.example.org`) && PathPrefix(`/realms/{realm:[a-z]+}/account`)
      priority: 2
      middlewares:
        - name: keycloak-account-headers
        - name: security-headers
    - kind: Rule
      match: Host(`keycloak.example.org`) && (PathPrefix(`/realms`,`/resources`,`/js`) || Path(`/robots.txt`))
      priority: 1
      middlewares:
        - name: keycloak-headers
        - name: security-headers
```
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-admin-headers
spec:
  headers:
    browserXssFilter: true # X-XSS-Protection: 1; mode=block
    contentTypeNosniff: true # X-Content-Type-Options: nosniff
    contentSecurityPolicy: >-
      upgrade-insecure-requests;
      base-uri 'self';
      default-src 'none';
      img-src 'self';
      font-src 'self';
      style-src 'self' 'unsafe-inline';
      script-src 'self' 'unsafe-inline';
      connect-src 'self';
      frame-src 'self';
      frame-ancestors 'self';
```
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-account-headers
spec:
  headers:
    contentSecurityPolicy: >-
      base-uri 'none';
      default-src 'none';
      img-src 'self' data:;
      font-src 'self';
      style-src 'self' 'unsafe-inline';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      connect-src 'self';
      frame-src 'self';
      frame-ancestors 'self';
```
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-headers
spec:
  headers:
    contentSecurityPolicy: >-
      base-uri 'none';
      default-src 'none';
      img-src 'self' data:;
      font-src 'self';
      style-src 'self';
      script-src 'self' 'unsafe-inline';
      connect-src 'self';
      frame-src 'self';
      frame-ancestors 'self';
```
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  headers:
    frameDeny: true # X-Frame-Options: DENY
    browserXssFilter: true # X-XSS-Protection: 1; mode=block
    contentTypeNosniff: true # X-Content-Type-Options: nosniff
```

Keycloak account management page requires even `unsafe-eval` script policy because of lines like `if (item.hidden && eval(item.hidden)) continue;`.

Also there are warnings in Chrome:
```
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
/realms/master/protocol/openid-connect/3p-cookies/step2.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
login-status-iframe.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
```

**Comment by jonkoops** [comment]
We've converted this to an epic to determine what is needed to improve the content security policy experience in Keycloak. Feel free to suggest any issues that should be considered a part of this, and I'll see if they can be added.

**Comment by dominiktopp** [comment]
Another little feature request regarding CSP:
We'd like to use [CSP violation reports](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only).
So we add the directives `report-to csp-endpoint; report-uri csp-endpoint` to our CSP header and also need to set the header `Reporting-Endpoints` to  `'csp-endpoint="/csp-report"`. Would be great if this would also be possible in Keycloak Admin UI.

**Comment by jonkoops** [comment]
@dominiktopp feel free to log this as a seperate feature request and ping me, I'll add it to this epic for evaluation.

**Comment by dominiktopp** [comment]
@jonkoops here it is: https://github.com/keycloak/keycloak/issues/32078

**Comment by dominiktopp** [comment]
I also created https://github.com/keycloak/keycloak/issues/32079 for using CSP nonce. At the moment we must rework our CSP and unsafe-inline is not permitted by our security department.

**Comment by jamesshuriff** [comment]
I have a patch that adds script-src support to ContentSecurityPolicyBuilder and the SecurityHeadersProvider. It can be used to inject hashes into the CSP header. The patch utilizes this to inject a hash for the BrowserHistoryHelper used for browser-based flows. It can be used for anything else on the server that generates on-the-fly JavaScript.

If this is desirable, I'll make a PR.

**Comment by jonkoops** [comment]
@jamesshuriff I would certainly welcome that, feel free to open up a PR for it. We'll have to do a close evaluation of our scripts, ideally all in-line scripts would be covered by this, but we can run it behind an experimental feature for a while to ensure folks can try it out.

**Comment by jonkoops** [comment]
Thanks @dominiktopp, I've linked them both here so they can be tracked under this epic.

**Comment by jamesshuriff** [comment]
@jonkoops I've opened #32125

**Comment by jamesshuriff** [comment]
@jonkoops as far as the inline scripts go, I'm writing a patch for the Freemarker provider to generate nonces that can be incorporated into templates so that the inline scripts don't have to be externalized. #32125 is more targeted towards on-the-fly JavaScript generated by the server.

**Comment by jonkoops** [comment]
> I'm writing a patch for the Freemarker provider to generate nonces that can be incorporated into templates so that the inline scripts don't have to be externalized.

Awesome, that is what I had in mind for those as well. Great stuff :+1:

**Comment by dominiktopp** [comment]
> @jonkoops as far as the inline scripts go, I'm writing a patch for the Freemarker provider to generate nonces that can be incorporated into templates so that the inline scripts don't have to be externalized. #32125 is more targeted towards on-the-fly JavaScript generated by the server.

@jamesshuriff this sounds exactly like https://github.com/keycloak/keycloak/issues/32079. Thank you. Unfortuantely I don't have the time to support on implementing this

**Comment by jamesshuriff** [comment]
@dominiktopp I'm finishing it up, now. I'm in the same boat you are, with security teams giving me a hard time over CSP.

**Comment by jamesshuriff** [comment]
I've opened #32144 to implement a NonceBean for Freemarker templates. It covers script-src and style-src. It also includes the previously discussed enhancements.

**Comment by ali-whizz** [comment]
To all the user like me, who is just looking around the exact solution of CSP error on admin console, here is the simple and most useful for this error. 
Set the env variable of host to your domain which is pointing to your server where you will deploye the final keycloak.

KC_HOSTNAME_ADMIN_URL=https://domain-name.xyz
KC_HOSTNAME_URL=https://domain-name.xyz

to set these you can use the run command of keyclaok(the command which you are using the run docker image of keycloak) or if you are dockerizing the whole application by creating the dockerfile and docker-compose file. then place the env variable in compose file.
you can reach me anytime for the assistance at ali.ravian1308@gmail.com

**Comment by siddhivinayak-sk** [comment]
Please confirm if we get this [commit](https://github.com/keycloak/keycloak/pull/32144/commits/d798f9bb4b5b535b10d92d156c10d1b930c6a8a5) then below issue can be handled:
![image](https://github.com/user-attachments/assets/66be9c44-0a05-4388-a1de-34016699b714)

**Comment by davidsyckle** [comment]
@jonkoops Thanks for the work and updates. I work for a team that could really use this improvement. Are the CSP improvements  scheduled for the 26.3.0 milestone?

**Comment by colorado-nate** [comment]
@jonkoops - We are using Keycloak, and it is failing our internal security scans because of this issue.  We've been waiting for over two years for a fix.  My company's security team is needing an update from you on when this will be fixed, or at some point will will need to explore options for replacing Keycloak.  Can you provide me with any confidence a date when this issue will be resolved?

**Comment by jedahan** [comment]
Is there a workaround? For me, downgrading from 26.3.0 to 25.0.1 fixed things.

**Comment by jonkoops** [comment]
@stianst can you add #43023 to the tasklist to track it?

**Comment by jonkoops** [comment]
Some possible inspiration for an API: https://docs.djangoproject.com/en/6.0/howto/csp/.

**Comment by MioG777829** [comment]
@stianst I see you modified the Hardened CSP milestone to: 26.7.0, Future.  Does this mean there is a timeline on coding cross-product changes necessary to have a working, security best practice value for the script-src directive?  Thank you for your comment, in advance.

**Comment by mikegpl** [comment]
Hi there! We ship Keycloak to enterprise customers and ended up building a locked-down login-page CSP ourselves - nonce-based, no `unsafe-inline`, running in production - so we have working implementations of #32079 and #32078, as a `SecurityHeadersProvider` plus theme changes.

**Question:** given the `Future` milestone and the unassigned subtasks, I take it there's no planned release for this - is that right? If so, would you accept contributions toward those two? #32078 in particular is small and self-contained. We'd rather upstream them than keep carrying them, and we're happy to port to current `main`.
