### ISSUE TITLE
Check if preview feature "Recovery codes" can be supported by default

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16740]
### Description

See the checklist on https://github.com/keycloak/keycloak/issues/16737

### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/26104
- [ ] https://github.com/keycloak/keycloak/issues/26105
- [ ] https://github.com/keycloak/keycloak/issues/26106
- [ ] https://github.com/keycloak/keycloak/issues/30702
- [ ] https://github.com/keycloak/keycloak/issues/30703
- [ ] https://github.com/keycloak/keycloak/issues/33933
- [ ] https://github.com/keycloak/keycloak/issues/38381
- [ ] https://github.com/keycloak/keycloak/issues/39213
- [ ] https://github.com/keycloak/keycloak/issues/39214
- [ ] https://github.com/keycloak/keycloak/issues/39245
- [ ] https://github.com/keycloak/keycloak/issues/39243
- [ ] https://github.com/keycloak/keycloak/issues/38994

**Comment by mposolda** [comment]
Follow-up tasks to supported recovery codes. We can address them if requested by Keycloak community (Contributions welcome as well):

- https://github.com/keycloak/keycloak/issues/39247
- https://github.com/keycloak/keycloak/issues/39249
- https://github.com/keycloak/keycloak/issues/39251

**Comment by mposolda** [comment]
Closing as all the required issues are done and `Recovery codes` feature is already marked as supported in latest Keycloak main. Should be supported since Keycloak 26.3.0
