### ISSUE TITLE
Implement the Federated Credential Management API

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16834]
The [Federated Credential Management API](https://developer.chrome.com/en/docs/privacy-sandbox/fedcm/) could be a possible standardized replacement for libraries such as Keycloak JS. And will allow a more natural way for users to sign into web applications.

Also, this might allow us to circumvent issues with 3rd party cookies now that more browsers are introducing state partitioning.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/23141
- [ ] https://github.com/keycloak/keycloak/issues/23146
- [ ] https://github.com/keycloak/keycloak/issues/23147
- [ ] Determine optional tasks from spec and when to implement them
```

**Comment by jonkoops** [comment]
@agektmr you might be interested to know we are looking to implement FedCM in Keycloak. If you have any recommendations for us feel free to pitch in.

**Comment by samuelgoto** [comment]
> @agektmr you might be interested to know we are looking to implement FedCM in Keycloak. If you have any recommendations for us feel free to pitch in.

This is really cool! LMK if you run into any challenges (or suggestions!) that I can help you with!

**Comment by jonkoops** [comment]
> This is really cool! LMK if you run into any challenges (or suggestions!) that I can help you with!

That would be great, we'll try to keep you all posted on our efforts :smile:

**Comment by epuronta** [comment]
This will be increasingly important as Chrome is planning to phase out support for 3rd party cookies altogether (https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/). We currently have several SPA solutions relying on 3rd party cookies for silent SSO. In the most difficult case, the SPA is embedded in another parent domain context within an iframe, making it as suspicious as possible from Chrome's point of view. :)

 Is this the right issue to track and contribute to the topic, or are there discussions going on elsewhere?

**Comment by deanmaster** [comment]
hello @ssilvert the milestone 24.0.0 is still possible ?

**Comment by jonkoops** [comment]
> Is this the right issue to track and contribute to the topic, or are there discussions going on elsewhere?

Yes, you can consider this a tracking issue around all FedCM related activities in regards to implementation.

**Comment by jonkoops** [comment]
> the milestone 24.0.0 is still possible ?

We cannot make any guarantees, but any implementation in Keycloak will remain experimental until the Federated Credential Management API specification is final.

**Comment by deanmaster** [comment]
hi @jonkoops do you think when FedCM is implemented the generic oidc-client-ts library can communication with this ? or you need a dedicate implement in this client.

**Comment by jonkoops** [comment]
> do you think when FedCM is implemented the generic oidc-client-ts library can communication with this ? or you need a dedicate implement in this client.

I don't know if this is something that `oidc-client-ts` team is interested in landing, so you would have to ask them, it's not affiliated to the Keycloak project.

That said, the FedCM API is pretty high level, so I think it would not be too much effort to just use it directly in your application. I'd recommend that you read the [FedCM developer guide](https://developers.google.com/privacy-sandbox/3pcd/fedcm-developer-guide) if you want to know more.

**Comment by vit-lebediev** [comment]
We use Keycloak in our company, and we'll be closely looking for this implementation. I'm a little bit worried about handling our SSO customer base after Chrome Privacy Sandbox will be widespread. 

I'd encourage everyone who uses keycloak & ends up seeing this discussion to give a 👍 to the original message in the thread to show KC team how popular this request is.

**Comment by jonkoops** [comment]
> I'm a little bit worried about handling our SSO customer base after Chrome Privacy Sandbox will be widespread.

Yes, we're pretty sure that it will impact the Silent Authentication and Session Management aspects of the spec. We've put measures in place to mitigate this as best as possible, but the fallbacks are not a great user experience. We're hoping that we can learn from FedCM and perhaps offer it as a migration path, and perhaps even replace Keycloak JS.

**Comment by tbroyer** [comment]
Correct me if I'm wrong (also, this might not be the best place to discuss this) but FedCM is only concerned with authentication, and won't give you an access token to call APIs of other applications. This means that you still need OAuth 2 in addition to FedCM, so Keycloak JS would still be useful to provide a more _integrated_ API.
Even if you don't need an access token, it also looks like the `IdentityCredential.token` needs to be validated by the RP, similar to an OIDC IDToken; this is specific to the IdP being used, so again Keycloak JS could codify those rules.
(fwiw, you'd still need an access token to call the UserInfo endpoint if you need more information about the user than his name, givenName, email address, and picture, so FedCM cannot entirely replace OIDC)

**Comment by samuelgoto** [comment]
> and won't give you an access token to call APIs of other applications.

This isn't accurate. FedCM doesn't open the response coming back from IdPs, so access tokens are a perfectly result for FedCM. We are working on extra UX surfaces to allow IdPs to have the opportunity to ask permissions using their own words (e.g. for non-profile scopes) [here](https://github.com/fedidcg/FedCM/issues/477), but from a technical standpoint, you can return an access token as a result of the FedCM API call.

> which will require that the spec is finalized as well. 

FedCM is a living spec, so you shouldn't expect it to ever be "finalized" in that sense: it will evolve as developers experiment and deploy and needs things.

That is, I think that the only way to move forward is to "build an experimental implementation" here and let us know what may be missing in your experience to fulfill your needs, rather than "wait until the specification is final": it won't ever be "final" until enough developers tell us what's missing.

For example, I think you are going to need a variation of [this](https://github.com/fedidcg/FedCM/issues/477), but we can't be certain until you build a prototype and gather implementation experience.

**Comment by deanmaster** [comment]
https://github.com/keycloak/keycloak/issues/16834#issuecomment-1886895152 
Hi @jonkoops I think you bring a very good point. The oidc-client-ts is working perfectly with Keycloak and eventually it's generic implement for OIDC protocol. Probably instead of having dedicate keycloak JS, you can think of using this library and eventually help them in the future with similar effort you put on keycloak JS with broader effect to the community.

**Comment by jonkoops** [comment]
> FedCM is a living spec, so you shouldn't expect it to ever be "finalized" in that sense: it will evolve as developers experiment and deploy and needs things.

Good to know, I really have to dig into this when I clear my backlog. Then we can safely assume that whatever is inside of the spec is considered stable.

> That is, I think that the only way to move forward is to "build an experimental implementation" here and let us know what may be missing in your experience to fulfill your needs, rather than "wait until the specification is final": it won't ever be "final" until enough developers tell us what's missing.

Yes, that is exactly what we are planning to do. We'll add this as an 'experimental' feature to Keycloak, meaning users will have to opt-in to the behaviour. We hope that we can gather enough feedback in a couple of releases to start promoting that to a preview and then a stable feature.

> For example, I think you are going to need a variation of https://github.com/fedidcg/FedCM/issues/477, but we can't be certain until you build a prototype and gather implementation experience.

We'd certainly be interested in helping you out testing this in real world deployments of Keycloak once the basic implementation is stable enough.

**Comment by jonkoops** [comment]
> Probably instead of having dedicate keycloak JS, you can think of using this library and eventually help them in the future with similar effort you put on keycloak JS with broader effect to the community.

Yes, exactly. That is also why I have been neglecting Keycloak JS a bit recently, aside from the 3rd-party cookie phaseout mitigations. We're not a massive team here at Keyloak, unlike some of our competitors in the more proprietary space, so we need to pick our battles.

We're going to evaluate what FedCM can do for our users, and hopefully supplant a large swath of the Keycloak JS use-cases, and making it a properly documented and supported protocol. For the remaining users that are on Keycloak JS and cannot move to FedCM, we will likely be recommending they move to a standard OpenID client, such as `oidc-client-ts`.

**Comment by rokk4** [comment]
> ... In the most difficult case, the SPA is embedded in another parent domain context within an iframe, making it as suspicious as possible from Chrome's point of view. :)
Where are doing the same and also using and hidden iframe for silent login to the embedded SPA. 
@epuronta is there any solution yet to keep this functionality?

**Comment by jonkoops** [comment]
Heads up for those involved, the implementation of FedCM in Keycloak is blocked on https://github.com/fedidcg/FedCM/issues/477#issuecomment-2047707555. I'll keep this thread up-to-date on any developments.

**Comment by thomasdarimont** [comment]
I gave this a quick spin and have a working prototype for a FedCM Keycloak integration.
My current setup involves a nginx reverse proxy to serve the `/.well-known/web-identity` from the idp root.
The rest is implemented with a custom `RealmResourceProvider` that serves the endpoints for the FedCM protocol.

Demo is here:
![keycloak-fedcm-prototype-v1](https://github.com/keycloak/keycloak/assets/314690/00880208-3824-485d-b10a-a3ea1bf2a336)

I'll share a link to the PoC later (if anyone is interested).

**Comment by epuronta** [comment]
> > ... In the most difficult case, the SPA is embedded in another parent domain context within an iframe, making it as suspicious as possible from Chrome's point of view. :)
> > Where are doing the same and also using and hidden iframe for silent login to the embedded SPA.
> 
> @epuronta is there any solution yet to keep this functionality?

We haven't come up with a good solution yet. Some proof-of-concepts exist with slight adjustments to the overall flow and Storage Access API prompts. It gets complicated though with lots of moving parts. Part of our product relies on exposing part of the functionality in a way that 3rd party integrators can embed the front end in their applications, so the setup cannot be too complicated.

We are following the ongoing discussion with great interest - happy to see that it is picking up speed!

**Comment by samuelgoto** [comment]
> I gave this a quick spin and have a working prototype for a FedCM Keycloak integration.

This is pretty cool!! Good stuff!

**Comment by samuelgoto** [comment]
> "FedCM 101" Talk slides from OAuth Security Workshop 2024

FWWI, I'm in at OSW this week! If you are following this thread and also at OSW, I'd love to meet you in person!

**Comment by samuelgoto** [comment]
> Heads up for those involved, the implementation of FedCM in Keycloak is blocked on https://github.com/fedidcg/FedCM/issues/477#issuecomment-2047707555. I'll keep this thread up-to-date on any developments.

I'll reply to the thread with more details, but it is great to hear that you are starting to nail down what's blocking you!

Much of this issue are things that we are actively working on and having working implementation in Chrome Canaries. Any chance that you could follow some of these instructions here to see if they unblock you?

https://github.com/fedidcg/FedCM/issues/477#issuecomment-2050654407
https://github.com/fedidcg/FedCM/issues/555
https://github.com/fedidcg/FedCM/issues/556
https://github.com/fedidcg/FedCM/issues/442#issuecomment-1949323416

HOWTO:

https://github.com/fedidcg/FedCM/blob/main/explorations/HOWTO-chrome.md#button-flow

**Comment by vaceksimon** [comment]
@thomasdarimont This is amazing. I am an intern at Keycloak and the FedCM API integration into Keycloak is a topic of my Bachelor Thesis. My current prototype implementation is roughly the same, so I am glad it seems I am taking the right steps. I hope it won't get me in trouble with my university, haha

**Comment by jonkoops** [comment]
> Any chance that you could follow some of these discussions and see if the proposals would suffice to you?

**Comment by samuelgoto** [comment]
> I am an intern at Keycloak and the FedCM API integration into Keycloak is a topic of my Bachelor Thesis.

I'd love to read that once you put that together!

> My current prototype implementation is roughly the same, so I am glad it seems I am taking the right steps.

I'm glad that you all are arriving at similar conclusions!

**Comment by jonkoops** [comment]
> Any chance that you could follow some of these discussions and see if the proposals would suffice to you?

Sure, I'll take a look at those discussions and see if we can pitch in. One of the proposals we're following is [FedCM as a trust signal for the Storage Access API](https://github.com/explainers-by-googlers/storage-access-for-fedcm), this seems like something that we could leverage to keep our existing flows pretty much the same, only using FedCM as a pre-flight,

**Comment by samuelgoto** [comment]
> One of the proposals we're following is FedCM as a trust signal for the Storage Access API, this seems like something that we could leverage to keep our existing flows pretty much the same, only using FedCM as a pre-flight,

FWIW, that's also available in chrome canaries behind a flag, so you should be able to try this too locally.

**Comment by samuelgoto** [comment]
> I'll start with that then, as it would be an easy addition to our existing flow as long as we can feature detect it.

We'll write down better instructions on how to give this a try, but I think it roughly is:

1) download chrome canaries
2) go to this URL and flip this flag chrome://flags#fedcm-with-storage-access-api
3) call the FedCM and SAA will be auto-granted as described [here](https://github.com/explainers-by-googlers/storage-access-for-fedcm?tab=readme-ov-file#saa-autogrants)

LMK if you struggle with to get this together.

**Comment by jonkoops** [comment]
Since we have the 25 release coming up I will kick this one to the next milestone.

**Comment by thomasdarimont** [comment]
This might be helpful as well: 
"Experimental implementation of FedCM - Continuation API": https://github.com/kg0r0/continuation-api

**Comment by thomasdarimont** [comment]
Some relevant update regarding Chromes [Privacy Sandbox](https://privacysandbox.com/intl/en_us/news/privacy-sandbox-update/): The planned third-party cookie phase-out is off the table - for now.

**Comment by jonkoops** [comment]
> At the same time, we recognize this transition requires significant work by many participants and will have an impact on publishers, advertisers, and everyone involved in online advertising. 

But too much emphasis on how this harms the ad industry rather than acknowledging there legitimate use-cases that would be harmed here. But it is nice to see this nonetheless.

> In light of this, we are proposing an updated approach that elevates user choice. Instead of deprecating third-party cookies, we would introduce a new experience in Chrome that lets people make an informed choice that applies across their web browsing, and they’d be able to adjust that choice at any time.

So it seems like this will still be implemented, but presented as a user-choice. Curious to see how this develops.
