### ISSUE TITLE
Keycloak UI Customization

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#19969]
### Description

This is the high-level epic used to aggregate various issues and discussions around end-user customization of the Keycloak Admin Console and Keycloak Account Console.

We will use a Quickstart to demonstrate the canonical method of customization for look-and-feel, as well as more intricate customization such as adding or modifying sections of the UI.

### Discussion

Discussed in UI Team Meetings and with management

### Issues

Here is a collection of issues and discussions related to this topic.  Issues and discussions with a check mark are completed/resolved.

- [ ] https://github.com/keycloak/keycloak/issues/17769
- [ ] https://github.com/keycloak/keycloak/discussions/19508
- [X] https://github.com/keycloak/keycloak/issues/19733
- [ ] https://github.com/keycloak/keycloak/discussions/9093
- [ ] https://github.com/keycloak/keycloak/discussions/13598
- [ ] https://github.com/keycloak/keycloak/issues/19761
- [ ] https://github.com/keycloak/keycloak/issues/19968
