### ISSUE TITLE
Admin UI incredibly slow with 300 realms

### ISSUE THREAD

**Issue by scoopex** [keycloak/keycloak#20453]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Our setup consists of hundreds of reals.

Since updating to Keycloak 20.0.5 the admin ui takes a really long time to fetch the list of tenants for the dropdown.

![2023-05-19_11-25](https://github.com/keycloak/keycloak/assets/288876/4f5b3386-d804-463e-90d7-23fc7ceeb258)

I reviewed the requests visible in the developer tools of chrome and identified the following request:
```
$ time curl 'http://localhost:42300/auth/admin/realms?briefRepresentation=true'   -H 'Accept: application/json, text/plain, */*'   -H 'Accept-Language: en-US,en;q=0.9,de;q=0.8'   -H 'Authorization: bearer REDACTED'   -H 'Connection: keep-alive'   -H 'DNT: 1'   -H 'Sec-Fetch-Dest: empty'   -H 'Sec-Fetch-Mode: cors'   -H 'Sec-Fetch-Site: same-origin'   -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'   -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"'   -H 'sec-ch-ua-mobile: ?0'   -H 'sec-ch-ua-platform: "Linux"'   --compressed
[{"id":"01038bb4-9b26-451e-8943-89d2c31436d2","realm":"REDACTED","enabled":true},....]
real	1m47,238s
user	0m0,007s
sys	0m0,009s
```
As you can see, that requires over 107 seconds to fetch the 307 tenants of that system.
Everytime i relogin to the master realm, i have to spend a few minutes :-)
(with Keycloak 17, this needed ~15 seconds) 

### Version

20.0.5

### Expected behavior

Make the admin-ui usable with 3 seconds :-)

### Actual behavior

See bug description

### How to Reproduce?

Create 500 realms.

### Anything else?

n/a
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/21555
- [ ] https://github.com/keycloak/keycloak/issues/21553
```

**Comment by ssilvert** [comment]
@scoopex Can you give this a try on the latest nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by scoopex** [comment]
Unfortunately not, because I have no simple  possibility to create 450 realms without my project environment.
Do you have a suggestion?

**Comment by scoopex** [comment]
I wrote a hacky script for reproduction and reproduced that with the latest release.
See: https://github.com/scoopex/keycloak-mass-realm

**Comment by jonkoops** [comment]
The performance of the API is a known issue I believe, but I cannot find any existing issue logged for it. Perhaps the changes to the store have influenced this behavior and worsened it?

**Comment by scoopex** [comment]
I suppose that this is the case. The speed with Keycloak 17 (our previous production release) was not a dream, but now the admin UI is significantly slower/inconvenient with Keycloak 20.

**Comment by ssilvert** [comment]
@scoopex Can you give the old admin console a try on the nightly build and look at the performance?  That will tell us if it's likely to be server side or client side.  You can install from the repo below.

https://github.com/ssilvert/old-keycloak-admin-console

**Comment by nfode** [comment]
Another problem seems to be the `/auth/admin/master/console/whoami` it loads all realms with their permissions for the given user and also takes a very long time the more realms you have.

**Comment by jonkoops** [comment]
@nfode could you file that as a seperate issue?

**Comment by edewit** [comment]
this is not an issue for the UI, because all we can do is call these endpoints

**Comment by nfode** [comment]
> @nfode could you file that as a seperate issue?

Should have checked the existing issues first. Seems like it is already known: https://github.com/keycloak/keycloak/issues/17455

**Comment by jonkoops** [comment]
Thanks, I appreciated that you checked for existing issues first. Saves us a bit of trouble :)

**Comment by edewit** [comment]
Right I think they may be related, but they are not the same let's re-open this one

**Comment by jmolbach** [comment]
We are experiencing the same issues. We have appx 300 realms now. Is there any known workarounds at the moment?

**Comment by edewit** [comment]
A workaround is to not use the dropdown to switch to another realm, but instead type it in the address bar

**Comment by edewit** [comment]
@scoopex the change in performance from keycloak 17 to 20 has to do with the saas support see https://github.com/keycloak/keycloak/discussions/11074

**Comment by jmolbach** [comment]
@edewit : I am afraid typing the realm admin url in the address bar is not a solution. The whoami times out, and the menu on the left is blank as a result of this.

**Comment by kkcmadhu** [comment]
i have the exact same problem and its painful, unfortunately, i  am struck with couple of production issues and not able to access the console because of too many realms (400+) 
Any way to expediate this issue.

**Comment by jonkoops** [comment]
Adding this to the v22 milestone, I don't expect this to get fixed soon, but this needs to be looked into.

**Comment by stianst** [comment]
Thinking out load around many realms scalability in admin console. There seems to be two primary issues:

* Listing realms due to realm drop-down - solution here I think is obvious and add pagination for the realms + some search/sever-side filtering

* WhoAmI endpoint - honestly don't know why it's adding roles for all realms, as the admin console is only displaying one realm at a time. So perhaps this can be relatively easily resolved by the whoAmI endpoint returning only roles the admin has for the currently selected realm

There's a few other things that may be issues with scaling large amounts of realms, but fixing those two issues should be a good start.

**Comment by jonkoops** [comment]
> Listing realms due to realm drop-down - solution here I think is obvious and add pagination for the realms + some search/sever-side filtering

Yes, absolutely this should be paginated. We can attempt to lazy-load this as the user scrolls down. Not sure how well PatternFly supports this, but I am sure we can work something out.

**Comment by mabartos** [comment]
As you've already mentioned, a possible scenario could be that after exceeding a particular count of realms (10?), the search bar would appear and the admin could search for the realm. 
PatternFly 4 provides a dropdown with filtering capability, which could be used here (f.e. [1]). 

I'm not sure how would the lazy-load scrolls down look like with a higher number of realms. I'd be more in favor of the filtering.

It'd also be good to have the possibility to mark particular realms as favorite, which could be always (with some limit) shown in the dropdown even when there are multiple realms (even hundreds of them) :P

IMHO, it could drastically improve the overall UX with the Admin UI in the multi-realms env.

[1] https://www.patternfly.org/v4/components/select#grouped-checkbox-input-with-filtering-and-custom-badging

**Comment by devlifealways** [comment]
Same issue here, we're over 200 realms and we started noticing slowness performance on Admin UI. We tried to tweak many aspects:
1. Database: increaseed **prepared transactions** with **XA enabled** on Quarkus + **max connections** 
2. Add more resources to Quarkus 
3. Tweaked inifinispan cache system (distributed)

Seems to help a little bit, but the display is still a little bit slow. Is there something else we can try to make UI smoother (didn't like the idea to mingle with database indexes ...etc.) ? 

Thank you,

**Comment by edewit** [comment]
@mabartos we already have implemented this behaviour but it's not searching the realms, but it's filtering, maybe it would be good to change it to searching instead

**Comment by edewit** [comment]
- [ ] Listing realms due to realm drop-down - solution here I think is obvious and add pagination for the realms + some search/sever-side filtering

- [ ] WhoAmI endpoint - honestly don't know why it's adding roles for all realms, as the admin console is only displaying one realm at a time. So perhaps this can be relatively easily resolved by the whoAmI endpoint returning only roles the admin has for the currently selected realm

**Comment by edewit** [comment]
closing as all tasks are done

**Comment by matt-rauch** [comment]
> closing as all tasks are done

@edewit just for clarity. In https://github.com/keycloak/keycloak/discussions/11074 there is also discussion about other scalability issues (e.g. duration for tenant creation) when working with a large amount of realms. 

Does this ticket only address the issues regarding working in the Admin console?
If so, are there any plans to support larger numbers of realms in a single keycloak cluster fully?

**Comment by edewit** [comment]
@matt-rauch right only did the tasks that are outlined in this issue that is something separate. Yes, there are multiple improvements being made to address there issues

**Comment by jmolbach** [comment]
@edewit , thanks for the update. Is the release version including those improvements decided yet?

**Comment by ca5p3r** [comment]
I am facing the same issue now again on latest Keycloak:v24.0.4

My current setup holds 570 realms, and the realms dropdown takes approximately 6 mins to load.
 
Request that takes time is:

`auth/admin/realms/master/ui-ext/realms/names?`
