### ISSUE TITLE
Write E2E tests for the Account Console v3

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#21244]
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/21245
- [ ] https://github.com/keycloak/keycloak/issues/21246
- [ ] https://github.com/keycloak/keycloak/issues/21247
- [ ] https://github.com/keycloak/keycloak/issues/21248
- [ ] https://github.com/keycloak/keycloak/issues/21249
- [ ] https://github.com/keycloak/keycloak/issues/21250
- [ ] https://github.com/keycloak/keycloak/issues/21251
```
