### ISSUE TITLE
Upgrade to PatternFly 5

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#21321]
We should upgrade all themes to PatternFly 5 as soon as these conditions are met:
1. PF5 is released
2. Keycloak 22 is final

All theme types should be upgraded so that everything is using the same PatternFly version.  (account, admin, login, welcome)

### Motivation

1. Welcome is still on PF3, so we need to get it upgraded to a supported version.
2. We should have everything on the same PatternFly version.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/21342
- [ ] https://github.com/keycloak/keycloak/issues/21343
- [ ] https://github.com/keycloak/keycloak/issues/21344
- [ ] https://github.com/keycloak/keycloak/issues/21345
- [ ] https://github.com/keycloak/keycloak/issues/21341
- [ ] https://github.com/keycloak/keycloak/issues/28197
- [ ] https://github.com/keycloak/keycloak/issues/26667
```

**Comment by jonkoops** [comment]
I'll take this one, I think we can easily upgrade Account v3 and the Admin Console. For the login, I think we should take some time to do that separately, mostly because the jump from PatternFly 3 - 4 is quite large.

**Comment by jonkoops** [comment]
@jenny-s51 I know you did some preliminary work on this under #21303. If you have some tips on how to best pick up from where you left, please let me know :smiley:

**Comment by ssilvert** [comment]
> I'll take this one, I think we can easily upgrade Account v3 and the Admin Console. For the login, I think we should take some time to do that separately, mostly because the jump from PatternFly 3 - 4 is quite large.

@jonkoops Login is actually the highest priority here.  We need to get off PF3 because it is no longer supported.

**Comment by mabartos** [comment]
AFAIK, we use PatternFly 4 for the login screens. Or do I miss something? 

https://github.com/keycloak/keycloak/pull/7470

**Comment by jonkoops** [comment]
@mabartos I can still see PatternFly 3 (and jQuery for some reason)[ being included](https://github.com/keycloak/keycloak/blob/5ee21ab6d10c27f154884c20cde0fe93a9352bd9/themes/src/main/resources/theme/keycloak/common/resources/package.json#L8-L9) in the common base for the the themes. But I guess this is not being used at all?

**Comment by jonkoops** [comment]
Upon closer inspection, it looks like the 'welcome' theme is still on PatternFly 3. Which is why it's still being listed as a dependency.

**Comment by jonkoops** [comment]
Okay, so things get even weirder. The login **is** using PatternFly 4. But it's not installed from the aforementioned package.json, instead the Account v2 theme has [a build step](https://github.com/keycloak/keycloak/blob/96b98dd2468921e71a2049d63fbbab8e89364ab2/themes/src/main/resources/theme/keycloak.v2/account/src/package.json#L12) that copies the dependencies it has into to the common theme.

Not only that, but it also seems that the login theme includes both PatternFly 3 **and** 4, as it [pulls in](https://github.com/keycloak/keycloak/blob/96b98dd2468921e71a2049d63fbbab8e89364ab2/themes/src/main/resources/theme/keycloak/login/theme.properties#L5) part of the dependencies from `node_modules` as well.

**Comment by jenny-s51** [comment]
@jonkoops the admin console builds and runs with the updates in #21303

With this v5 update, the big lift on the Keycloak side will likely be updating the form elements to use FormHelperText, HelperText, and HelperTextItem directly inside children - I marked all those instances in #21303 with `TODO` statements. There are also some event handlers that will need their parameters reordered.

You may notice some visual differences as well and should be able to fix these by updating any hardcoded `pf-c-[component]` instances to `pf-v5-c-[component]`.

We hope to have official PF5 release numbers next week 🙂

**Comment by jonkoops** [comment]
Great, I'll have a gander once the stable is out!
