### ISSUE TITLE
Dependency cleanup related issues

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#21356]
### Description

This serves as an umbrella issue to collect all the reported issues regarding the dependency cleanup.

List of the reported issues:

- [x] https://github.com/keycloak/keycloak/issues/20570
- [x] https://github.com/keycloak/keycloak/issues/15870
- [ ] https://github.com/keycloak/keycloak/issues/9258
- [x] https://github.com/keycloak/keycloak/issues/9075

List of the follow-up tasks:
- [x] https://github.com/keycloak/keycloak/issues/21360
- [x] https://github.com/keycloak/keycloak/issues/21363
- [x] https://github.com/keycloak/keycloak/issues/21364
- [x] https://github.com/keycloak/keycloak/issues/21391
- [x] https://github.com/keycloak/keycloak/issues/21392
- [x] https://github.com/keycloak/keycloak/issues/21393

**Comment by vmuzikar** [comment]
@Pepo48 Moved this to 26. Can you please check if this epic is still relevant when you get a chance? Feel free to close it.
