### ISSUE TITLE
DPoP: promote from preview to supported

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#22311]
### Description

DPoP is preview feature since Keycloak 23. The related epic for DPoP preview support is keycloak/keycloak#21916 

This task is about promote DPoP to supported. We can wait for the feedback from the community if something is reported in Keycloak 23. Also we can consider if we should improve something (EG. extract DPoP a bit more from the core classes and plug it as independent extension through client policies).

### Discussion

https://github.com/keycloak/keycloak/issues/21916 (See the other discussions linked from this epic).

### Tasks

- [x] https://github.com/keycloak/keycloak/issues/30181
- [x] https://github.com/keycloak/keycloak/issues/30179
- [x] https://github.com/keycloak/keycloak/issues/34842
- [x] https://github.com/keycloak/keycloak/issues/31970
- [x] https://github.com/keycloak/keycloak/issues/34990
- [x] https://github.com/keycloak/keycloak/issues/36261
- [x] https://github.com/keycloak/keycloak/issues/36475
- [x] https://github.com/keycloak/keycloak/issues/36476
- [x] https://github.com/keycloak/keycloak/issues/38333
- [x] https://github.com/keycloak/keycloak/issues/39761
- [x] https://github.com/keycloak/keycloak/issues/35441
- [x] https://github.com/keycloak/keycloak/issues/33942
- [x] https://github.com/keycloak/keycloak/issues/42030
- [x] https://github.com/keycloak/keycloak/issues/42031
- [x] https://github.com/keycloak/keycloak/issues/42286
- [x] https://github.com/keycloak/keycloak/issues/42706
- [x] https://github.com/keycloak/keycloak/issues/42740
- [x] https://github.com/keycloak/keycloak/issues/26277
- [x] https://github.com/keycloak/keycloak/issues/42746
- [x] https://github.com/keycloak/keycloak/issues/42728
- [x] https://github.com/keycloak/keycloak/issues/42032

### Related

- https://github.com/keycloak/keycloak/issues/42810
- https://github.com/keycloak/keycloak/issues/12682

### Optional tasks

- [ ] https://github.com/keycloak/keycloak/issues/39042
- [ ] https://github.com/keycloak/keycloak-client/issues/162
- [ ] https://github.com/keycloak/keycloak-js/issues/8
- [ ] https://github.com/keycloak/keycloak/issues/42813
- [ ] https://github.com/keycloak/keycloak/issues/42814
- [ ] https://github.com/keycloak/keycloak/issues/21921

**Comment by smandlavdiya** [comment]
when it’s planned to be fully supported?

**Comment by jonkoops** [comment]
@smandlavdiya we don't give estimates of when features become fully supported, they will be ready when they are ready. In the meantime check out the linked issues to see the progress.

**Comment by mposolda** [comment]
Closing as all the required subtasks were finished. DPoP should be supported feature in Keycloak 26.4.0!
