### ISSUE TITLE
Enable social login tests

### ISSUE THREAD

**Issue by tondrusk** [keycloak/keycloak#22886]
This Epic is used for tracking the progress of enabling and fixing the social login tests.

```[tasklist]
### Issues
- [ ] https://github.com/keycloak/keycloak/issues/22282
- [ ] https://github.com/keycloak/keycloak/issues/22461
- [ ] https://github.com/keycloak/keycloak/issues/22657
- [ ] https://github.com/keycloak/keycloak/issues/22661
- [ ] https://github.com/keycloak/keycloak/issues/23252
```
