### ISSUE TITLE
Extracting more of the "automatically added" claims to protocol mappers

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23727]
### Description

After we realize first 2 milestones of lightweight access tokens (epic #21186), we will have ability to have lightweight access tokens without almost none of user PII informations. We currently have claims like those always added to access token (those are currently hardcoded and not added by protocol mappers): `exp`, `iat`, `auth_time`, `jti`, `iss`, `aud`, `sub`, `typ`, `azp`, `nonce`, `session_state`, `sid`, `scope`.

However such access token currently still has relatively lots of claims. We can think about "extracting" some more claims, which are currently always added to access token to be added by protocol mappers. Which means that we would have some additional flexibility as administrator will have ability to avoid some of those claims in the access token. When we extract adding those via protocol mappers, it means that we can omit some of them from the access token.

We can probably introduce some new client scope (like `basic` or something like that?) and add the default protocol mappers to it. We will need some migration to always add this client scope to all existing clients.

Regarding claims, it seems that at least those claims are ideal candidates (we may need subtasks to iteratively extract those claims into protocol mappers instead of doing it in one big PR):
- `nonce` - This claim can be possibly removed even from the "Default" access token as it probably makes sense only for ID Token? NOTE: We may still need some option for allow adding `nonce` due the backwards compatibility as client applications may rely on it (Especially our keycloak.js adapter currently rely on nonce being present according to https://github.com/keycloak/keycloak/pull/26891 . So if we remove nonce, people will need to update their keycloak.js to the version where this PR is fixed or still add mapper manually to add nonce to access/refresh tokens).
- auth_time - This claim not needed in lightweight access token in most of the cases
- sub - The claim `sub` is needed just for "Service accounts" as there is no user session. But Keycloak itself typically doesn't need this claim (at introspection endpoint, user info endpoint etc). Maybe we can have separate protocol mapper implementation for `sub` with flag like "Add only to service accounts" to have ability to add `sub` claim only to service accounts, but not during regular authentications? We have already subtask #21185 
- `sid` or `session_state` - this claim is currently duplicated in access token (and also in ID Tokens and Refresh token). We can maybe have protocol mappers to make sure that this claim is added only once (not two times). This might apply also for ID Token and Refresh token and others.
- Can we have some more?

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/21185
- [ ] https://github.com/keycloak/keycloak/issues/26893
- [x] https://github.com/keycloak/keycloak/issues/27623
- [x] https://github.com/keycloak/keycloak/issues/27624
- [ ] https://github.com/keycloak/keycloak/issues/24466
- [ ] https://github.com/keycloak/keycloak/issues/28460
- [ ] https://github.com/keycloak/keycloak/issues/28567
- [ ] https://github.com/keycloak/keycloak/issues/28624
- [x] https://github.com/keycloak/keycloak/issues/28661
```

**Comment by stianst** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/26893

**Comment by mposolda** [comment]
All tasks are finished! I consider that milestone 3 can be successfully closed now.
