### ISSUE TITLE
Authentication improvements for the "You are already logged-in"

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23879]
### Description

See [KEYCLOAK-5179](https://issues.redhat.com/browse/KEYCLOAK-5179) and https://github.com/keycloak/keycloak/issues/12406

This is infamous Keycloak bug, which is reported often by community and customers as well as RedHat employees and users due the fact that it often occurs when logging to Red Hat applications (for instance JIRA) via sso.redhat.com

This epic refers the main task (reported bug) https://github.com/keycloak/keycloak/issues/12406 as well as other related enhancements.

### Discussion

https://github.com/keycloak/keycloak/issues/12406 and https://issues.redhat.com/browse/KEYCLOAK-5179

```[tasklist]
### Tasks
- [x] #12406
- [x] #19555
- [x] #23880
- [ ] #24112
- [ ] https://github.com/keycloak/keycloak/issues/27879
- [ ] https://github.com/keycloak/keycloak/issues/27880
- [ ] https://github.com/keycloak/keycloak/issues/28412
```

**Comment by mposolda** [comment]
Postponing. Some parts of this were done in Keycloak 23, but #24112 may probably need to postponed and hence postponing also whole epic to Keycloak 24.

**Comment by mposolda** [comment]
All tasks are done. No more work planned for this epic.
