### ISSUE TITLE
Declarative user profile enable by default

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#23907]
### Description

In this epic, we should look at the issues that must be addressed in order to enable the declarative user profile to realms by default.

### Discussion

https://github.com/keycloak/keycloak/issues/16741

### Motivation

To become a supported feature, the declarative user profile must be enabled by default to new realms.
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/25151
- [ ] https://github.com/keycloak/keycloak/issues/25153
- [x] Make sure Account v3 is supported
- [ ] https://github.com/keycloak/keycloak/issues/24250
- [ ] https://github.com/keycloak/keycloak/issues/25985
- [ ] https://github.com/keycloak/keycloak/issues/26552
- [ ] https://github.com/keycloak/keycloak/issues/26564
- [ ] https://github.com/keycloak/keycloak/issues/23539
```

```[tasklist]
### Documentation related tasks
- [ ] https://github.com/keycloak/keycloak/issues/26742
- [x] Documentation for migrating realms using custom attributes
- [ ] https://github.com/keycloak/keycloak/issues/26154
- [ ] https://github.com/keycloak/keycloak/issues/26155
- [ ] https://github.com/keycloak/keycloak/issues/25979
- [ ] https://github.com/keycloak/keycloak/issues/25984
- [ ] https://github.com/keycloak/keycloak/issues/26469
- [ ] https://github.com/keycloak/keycloak/issues/26634
- [ ] https://github.com/keycloak/keycloak/issues/26917
- [ ] https://github.com/keycloak/keycloak/issues/26932
```

**Comment by MohammedNoureldin** [comment]
Hi @pedroigor, could you consider this also? https://github.com/keycloak/keycloak/issues/23970

This is going to be helpful, particularly to automate the configuration after deploying keycloak.

**Comment by pedroigor** [comment]
@MohammedNoureldin Sure, added to https://github.com/keycloak/keycloak/issues/23905. @vramik is already on it.

**Comment by pedroigor** [comment]
@mposolda @marekbnn There we go ... Thanks for all the help!
