### ISSUE TITLE
Review serverinfo endpoint and remove data related to provider and component metadata

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#24360]
### Description

Looks like the `ServerInfoAdminResource` can't scale and also doesn't allow fetching server metadata on a per-realm basis.

The reason why I think it won't scale is that the response is quite expensive to compute and it gets worse as we add more providers to the server. A lot of metadata for providers and components are available from the response whereas they should be fetched on-demand and on a per-realm basis to support rendering their configuration properties more dynamically.

This epic is about tracking the data we want to remove from the serverinfo endpoint:

* [ ] System-wide data (as suggested by @stianst they are related to server metrics)
* [ ] Crypto data 
* [ ] Social provider data
* [ ] Identity Providers data
* [ ] Built-in and custom providers data
* [ ] Protocol mappers data
* [ ] Client installation data
* [ ] Password policies data

Ideally, the serverinfo should return the minimal set of data to be render the dashboard (and review what is there) and the tab where administrators can look for installed providers should probably be fetching data from the server on-demand.

### Discussion

Discussion in mailing list

### Motivation

Improve responses from the server info endpoint and the administration console itself by reducing the amount of data returned by the server info endpoint.
