### ISSUE TITLE
Supporting OAuth 2.1

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#25141]
### Description

OAuth 2.1 is a securiy-hardened version of OAuth 2.0.
- The OAuth 2.1 Authorization Framework
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09

It is still an internet draft, but it has been discussed about 3 years. It seems to be matured considerably, therefore it is worth supporting OAuth 2.1 to Keycloak.

### Discussion

https://github.com/keycloak/keycloak/discussions/24043

### Details

It is preferable if we could support OAuth 2.1 by only using [Client Policies](https://www.keycloak.org/docs/latest/server_admin/index.html#_client_policies) because it does not affect Keycloak's core codes.

The requirements of OAuth 2.1 are different on each a confidential client and a public client.
Therefore, a profile of OAuth 2.1 for each type should be created; `oauth-2-1-for-confidential-client` and `oauth-2-1-for-public-client` . By using policies of Client Policy `ClientAccessTypeCondition` , we can apply each default profile depending on client's access type (confidential or public).

According to [the specification](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#name-differences-from-oauth-20):

> Refresh tokens for public clients must either be sender-constrained or one-time use.

Enforcing one-time use of a refresh token might be difficult compared with enforcing sender-constrained refresh token. Therefore, an client policy's executor for enforcing sender-constrained refresh token needs to be created.

We already have such the executor for enforcing sender-constrained refresh token in [OAuth MTLS](https://datatracker.ietf.org/doc/html/rfc8705). However, it is difficult for a public client to apply OAuth MTLS. Therefore, an executor for enforcing sender-constrained refresh token in [DPoP](https://datatracker.ietf.org/doc/html/rfc9449).

Summarzing the above points, the issue can be broken down onto the following sub-issues:

1. Supporting OAuth 2.1 for confidential clients - creating a default profile `oauth-2-1-for-confidential-client`
2. Creating an executor for enforcing sender-constrained refresh token in DPoP.
3. Supporting OAuth 2.1 for public clients - creating a default profile `oauth-2-1-for-public-client`, which consists of a default profile `oauth-2-1-for-confidential-client` and the executor created in the sub-issue 2.
4. (option) Creating an executor for enforcing a one-time use refresh token.

DPoP is still a preview feature in Keycloak 23, therefore, the sub-issue 3 might be resolved after DPoP is an official feature.

- [x] https://github.com/keycloak/keycloak/issues/25637
- [x] https://github.com/keycloak/keycloak/issues/25314
- [x] https://github.com/keycloak/keycloak/issues/25315
- [x] https://github.com/keycloak/keycloak/issues/25316

## Policy

The policy for determining a default OAuth 2.1 profile is as follows:

- We only follow points marked with MUST, REQUIRED, SHALL, SHOULD or RECOMMENDED by considering [RFC 2119 Key words for use in RFCs to Indicate Requirement Levels](https://datatracker.ietf.org/doc/html/rfc2119.html).

```
1. MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

2. MUST NOT   This phrase, or the phrase "SHALL NOT", mean that the
   definition is an absolute prohibition of the specification.

3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.
```

- We create a default OAuth 2.1 profile for confidential clients and for public clients because each has different requirements. They are implemented as client policies' default profiles.

### Redirect URIs
 - On client registration and update, Keycloak requres a client to registrate at least one valid redirect URI. If not, Keycloak returns an error. ([the 1st paragraph of 2.3.1. Registration Requirements](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-2.3.1))
 - As a valid redirect URI, Kecloak allows both IPv4 and IPv6 loopback addresss. ([the 7th paragraph of 8.4.2. Loopback Interface Redirection](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-8.4.2))
 ```
     IPv4 loopback address:
       http://127.0.0.1:{port}/{path}
      example:
       http://127.0.0.1:51004/oauth2redirect/example-provider
     IPv6 loopback address:
       http://[::1]:{port}/{path}
      example:
       http://[::1]:61023/oauth2redirect/example-provider
 ```
 - Keycloak does not allow a loopback address using "localhost". ([the 9th paragraph of 8.4.2. Loopback Interface Redirection](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-8.4.2))
 - When Keycloak receives an authorization request from a client, Keycloak needs to exactly match redirect_uri parameter of the request with one of registered redirect URIs by [Simple String Comparison in RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html#section-6.2.1) with an exception for a loopback address, where an exact match is required except for the port URI component. If not, Keycloak returns an error to a browser. ([the 1st paragraph of 2.3.1. Registration Requirements](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-2.3.1))
 - Keycloak allows a private-use URI scheme inclluding at least one period (.) . ([the 4th paragraph of 2.3.1. Registration Requirements](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-2.3.1)), ([the 4th paragraph of 8.4.3. Private-Use URI Scheme Redirection](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-8.4.3))
 ```
  example:
        com.example.app:/oauth2redirect/example-provider
 ```
 - Except for a loopback address and private-use URI scheme, Keycloak only allows https scheme URI.
 - Keycloak does not allow a URI including URI fragment. ([the 3rd paragraph of 2.3. Client Redirection Endpoint](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-2.3))

### Sender-constrained Access Token
 - Keycloak enforces a sender-constrained access token by OAuth MTLS. ([the 2nd paragraph of 5.4. Sender-Constrained Access Tokens](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-5.4))

### Sender-constrained Refresh Token
 - The specification does not mention a sender-constraned refresh token for a confidential client, but Keycloak enforces a sender-constrained refresh token by OAuth MTLS because Keycloak realizes both sender-constrained access and refresh tokens by OAuth MTLS.

### Proof Key for Code Exchange and CSRF contermeasures
 - Keycloak enforces PKCE, but does not enforce using state or nonce as CSRF contermeasure. ([the 1st paragraph of 2.3.3. Preventing CSRF Attacks](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-2.3.3)) ([the 4th paragraph of 7.10. Cross-Site Request Forgery](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-7.10))

### Client Authentication Methods
 - Keycloak only allows signed JWTs ("Private Key JWT") and X.509 client authentication. ([the 3rd paragraph of 2.4. Client Authentication](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-2.4))

### Not Allow Implicit Grant
 - Keycloak does not allow a client to request an implicit grant. ([4. Grant Types](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#name-grant-types))

### Not Allow Resource Owner Password Credentials Grant
 - Keycloak does not allow a client to request a resource owner password credentials grant. ([4. Grant Types](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#name-grant-types))

### Others Not Specified by OAuth 2.1 Specification
 - keycloak applies `consent-required` and `full-scope-disabled` the same as other default FAPI profiles.

### Redirect URIs
 The same as for confiential clients.

### Sender-constrained Tokens
 - Keycloak enforces a sender-constrained access token by DPoP. ([the 2nd paragraph of 5.4. Sender-Constrained Access Tokens](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-5.4))

### Sender-constrained Refresh Token
 - Keycloak enforces a sender-constrained refresh token by DPoP. ([the 14th paragraph of 4.3.1. Token Endpoint Extension](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-09#section-4.3.1))

### Proof Key for Code Exchange and CSRF contermeasures
 The same as for confiential clients.

### Client Authentication Methods
 No client authentication for a public client.

### Not Allow Implicit Grant
 The same as for confiential clients.

### Not Allow Resource Owner Password Credentials Grant
 The same as for confiential clients.

### Others Not Specified by OAuth 2.1 Specification
 The same as for confiential clients.

**Comment by mposolda** [comment]
@tnorimat Maybe you know that Keycloak has switch `Revoke refresh token`. It is in admin console in tab `Realm settings` -> `Tokens` . When ON, refresh token might be single-use. It is currently per-realm switch. I am not 100% sure if we strictly need more fine-grained than per-realm level, but it might be probably doable (for example enable just for public clients conditionally based on client policy).

**Comment by tnorimat** [comment]
@mposolda Yes, `Realm settings` -> `Tokens` can realize an one-time use refresh token. This setting is per-realm so that this setting is applied to all clients in realm. If a keycloak user allows it for their use-case, they can apply OAuth 2.1 for public clients without enforcing DPoP.
IMO, there are the following options about it:

1. Writing documentation about it
2. Adding a feature of per-client overriding `Realm settings` -> `Tokens`  realm setting, and add an executor for enforcing the one-time use refresh token settings for a client

The option 1 might be OK for the moment. If you prefer the option 2, I will work on it. WDYT?
