### ISSUE TITLE
Investigate possible perf enhancements for Quarkus integration tests

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#25931]
### Description

`Quarkus IT (ubuntu-latest, zip)` currently [take over than an hour](https://github.com/keycloak/keycloak/actions/runs/7403842389/job/20144638050) while other tests need only <40 minutes. This makes it a bottleneck and we should investigate possible improvements.

```[tasklist]
### Tasks
- [x] https://github.com/keycloak/keycloak/issues/29117
- [x] https://github.com/keycloak/keycloak/issues/29118
- [ ] https://github.com/keycloak/keycloak/issues/34058
- [ ] https://github.com/keycloak/keycloak/issues/34927
```

**Comment by shawkins** [comment]
@vmuzikar at this point we don't have any more tasks identified. Do you want to resolve this?

**Comment by vmuzikar** [comment]
@shawkins Yes, let's resolve this. Nice work, thanks.
