### ISSUE TITLE
Support OpenID for Verifiable Credentials(OID4VC)

### ISSUE THREAD

**Issue by wistefan** [keycloak/keycloak#25936]
### Description

OpenID for Verifiable Credentials has been discussed a lot in the Self-Sovereign Identity (SSI) especially due to European Commission having released the [EUDI-Wallet Framework](https://digital-strategy.ec.europa.eu/en/library/european-digital-identity-wallet-architecture-and-reference-framework) for eIDASv2. The later tends to chose OID4VC as a protocol to issue Verifiable Credential (VC) and to present Verifiable Presentation (VP). In order to be used in dezentralized IAM usecases, Keycloak should support protocols summarized as OID4VC.

In terms of OID4VC, Keycloak should be able to fulfill multiple roles by offering the protocols connected with the roles:
> :warning: Some of the specs are still in "draft" status. However, they are already gaining a lot of traction in various projects and beeing referenced in official documents like eIDAS-2 or  EUDI-Wallet.

*  Credentials Issuer - Keycloak should be able to issue credentials by implementing the [OpenId for Verifiable Credentials Issuance(OID4VCI) Spec](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html), the supported formats should be:
    * [JWT-VC](https://identity.foundation/jwt-vc-presentation-profile/)
    * [SD-JWT-VC](https://www.ietf.org/archive/id/draft-fett-oauth-selective-disclosure-jwt-02.html)
    * [VCDM](https://www.w3.org/TR/vc-data-model/)
    * [mDL](https://www.iso.org/standard/69084.html)
 * Credentials and Presentation Verification: Keycloak should be able to receive and verify credentials. It should support the protocls:
    * [OID4VP](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html) 
    * [SIOP-2](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html)

### Discussion

https://github.com/keycloak/keycloak/discussions?discussions_q=is%3Aopen+label%3Aarea%2Foid4vc

```[tasklist]
### Issues
- [ ] #25937
- [ ] #25940
- [ ] #25941
- [ ] #25942
- [ ] #25943
- [ ] #25638
- [ ] #25945
- [ ] #26936
- [ ] #28968
- [ ] #29309
- [ ] #29620
- [ ] #29627
- [ ] #29634
- [ ] #29724
- [ ] #29805
- [ ] https://github.com/keycloak/keycloak/issues/29852
- [ ] https://github.com/keycloak/keycloak/issues/29885
- [ ] #30419
- [ ] https://github.com/keycloak/keycloak/issues/29725
- [ ] https://github.com/keycloak/keycloak/issues/26328
- [ ] https://github.com/keycloak/keycloak/pull/30127
- [ ] https://github.com/keycloak/keycloak/issues/30458
- [ ] https://github.com/keycloak/keycloak/issues/30525
- [ ] https://github.com/keycloak/keycloak/issues/30907
- [ ] https://github.com/keycloak/keycloak/issues/30902
```

### Motivation

Verifiable Credentials, Self-Sovereign Identity and Decentralized IAM gaining a lot of importance and become part of various regulations and specifications. While currently various implementations in connection to the protocols arise, it would be good to have that in Keycloak, because:
* its already a well-established and maintained IAM project
* trusted and used already in many of the connected use-cases
* Keycloak could provide backward-compatibility(e.g. support "normal" IAM) while allowing its users to also support the decentralized mechanisms

**Comment by tnorimat** [comment]
@wistefan The issues include this issue itself (https://github.com/keycloak/keycloak/issues/25936).

**Comment by wistefan** [comment]
> @wistefan The issues include this issue itself (#25936).

Could be called "self-contained";) I removed it, thanks for mentioning.

**Comment by francis-pouatcha** [comment]
@wistefan can you please add issue #25638 to the list?

**Comment by Yann39** [comment]
We are also waiting for this functionality, we're part of a pilot project using the European Blockchain Services Infrastructure (EBSI) and are already using Keycloak in our organization, it would be great to be able to use a native implementation of OID4VC in keycloak without using third-party plugins.

**Comment by francis-pouatcha** [comment]
@wistefan can you please add these issues to the list: 
- #30525 
- #30907

**Comment by mposolda** [comment]
I am closing this issue as we agreed on the OAuth SIG meeting. This gives some overview on what aspects of OID4VC are available in Keycloak 26 as those are the child issues of this epic.

The OID4VC is available in Keycloak 26 still as an experimental and there is still lots of work in progress before it is officially supported. There are follow-up issues like for example #32961 and #32772 .

@francis-pouatcha  I've added label `area/oid4vc` for the issues you mentioned in the last comment. Some of them are already available as issues on the epic #32961 . For some others, feel free to create additional epic if you want to track them on single place.

**Comment by lucagiorgino** [comment]
Hello everyone, I see that different closed issues cover the OID4VCI standard. May I ask what is the status of the implementation of OID4VP and SIOP-2?
