### ISSUE TITLE
Support AWS JDBC Wrapper

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#26496]
### Description

The [Amazon Web Services (AWS) JDBC Driver](https://github.com/awslabs/aws-advanced-jdbc-wrapper) adds advanced functionalities for databases hosted on AWS. 

It also resolves the issue that after a failover of the writer instance the existing DB connections point to the now read-only database, at least for AWS Databases:
* https://github.com/keycloak/keycloak/issues/24493

This would also resolve the following discussions: 
* https://github.com/keycloak/keycloak/discussions/15292

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/698
- [ ] https://github.com/keycloak/keycloak/issues/27123
- [ ] https://github.com/keycloak/keycloak/issues/27211
```

**Comment by ahus1** [comment]
All items complete
