### ISSUE TITLE
A/P documentation up-to-date for Keycloak HA to be GA

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#26491]
### Description

The high availability documentation for Keycloak HA needs to be up-to-date to be GA

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/26776
- [ ] https://github.com/keycloak/keycloak/issues/26490
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/704
- [ ] https://github.com/keycloak/keycloak/issues/26781
- [ ] https://github.com/keycloak/keycloak-benchmark/pull/710
- [ ] https://github.com/keycloak/keycloak/issues/26849
- [ ] https://github.com/keycloak/keycloak/issues/27078
- [ ] https://github.com/keycloak/keycloak/issues/27084
- [ ] https://github.com/keycloak/keycloak/issues/27121
- [ ] https://github.com/keycloak/keycloak/issues/27211
```

**Comment by ahus1** [comment]
All items complete
