### ISSUE TITLE
Cookie refactoring

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#26503]
### Description

Cookie management in Keycloak is not great. The code is spread around the place making it hard to keep cookies consistent, or provide some configuration around cookies. There's also quite a lot of old workarounds that are no longer needed that can be cleaned-up.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/26416
- [ ] https://github.com/keycloak/keycloak/pull/26462
- [ ] https://github.com/keycloak/keycloak/pull/26326
- [ ] https://github.com/keycloak/keycloak/issues/26500
- [x] Migrate all cookies to Cookie Provider
- [ ] https://github.com/keycloak/keycloak/issues/26557
- [ ] https://github.com/keycloak/keycloak/issues/28465
- [ ] https://github.com/keycloak/keycloak/issues/16181
- [ ] https://github.com/keycloak/keycloak/issues/16770
- [ ] https://github.com/keycloak/keycloak/issues/26103
- [ ] https://github.com/keycloak/keycloak/issues/26813
- [ ] https://github.com/keycloak/keycloak/issues/26847
```

**Comment by Ketec** [comment]
Will this enable support for SameSite configuration?
https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct

Google is on its way to disabling third-party cookies - started with select users this year.
It's a matter of months before they disable them by default.

So within months, Keycloak sessions essentially cease to exist, forcing users to log in every time they open the browser.
