### ISSUE TITLE
Stabilize WebAuthn tests

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#27164]
### Description

There is a number of the WebAuthn tests that are unstable. See https://stianst.github.io/keycloak-dashboard/tests#flaky-tests for the full list, but some are listed below. 

Note from @mabartos : AFAIK, the good first step to stabilize the WebAuthn tests is to upgrade Selenium 4.x version. But prior that, the Arquillian deps need to be upgraded as well. https://github.com/arquillian/arquillian-extension-drone/pull/401

### Discussion

N/A

### Issues
- [x] https://github.com/keycloak/keycloak/issues/20777
- [x] https://github.com/keycloak/keycloak/issues/21575
- [x] https://github.com/keycloak/keycloak/issues/21203
- [x] https://github.com/keycloak/keycloak/issues/23884
- [x] https://github.com/keycloak/keycloak/issues/23463
- [x] https://github.com/keycloak/keycloak/issues/24909
- [x] https://github.com/keycloak/keycloak/issues/21785
- [x] https://github.com/keycloak/keycloak/issues/25445
- [x] https://github.com/keycloak/keycloak/issues/20833
- [x] https://github.com/keycloak/keycloak/issues/20476

**Comment by mposolda** [comment]
Moving to 27 for now as the WebAuthn tests are not flaky anymore since March 2024.

**Comment by mabartos** [comment]
The stability of WebAuthn tests should be fine now, as all major issues were resolved. Closing now.
