### ISSUE TITLE
Durable sessions across restarts

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#28265]
### Description

This epic tracks the progress of having durable sessions across Keycloak restarts

### Discussion

* https://github.com/keycloak/keycloak/discussions/28271

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/27976
- [x] Create a discussion for track community feedback
- [ ] https://github.com/keycloak/keycloak/issues/28318
- [ ] https://github.com/keycloak/keycloak/issues/28501
- [ ] https://github.com/keycloak/keycloak/issues/28862
- [ ] https://github.com/keycloak/keycloak/issues/29141
- [ ] https://github.com/keycloak/keycloak/issues/29139
- [ ] https://github.com/keycloak/keycloak/issues/29140
- [ ] https://github.com/keycloak/keycloak/issues/29144
- [ ] https://github.com/keycloak/keycloak/issues/29264
- [ ] https://github.com/keycloak/keycloak/issues/29319
- [ ] https://github.com/keycloak/keycloak/issues/29218
- [ ] https://github.com/keycloak/keycloak/issues/29392
- [ ] https://github.com/keycloak/keycloak/issues/29489
- [ ] https://github.com/keycloak/keycloak/issues/29375
- [ ] https://github.com/keycloak/keycloak/issues/29561
- [ ] https://github.com/keycloak/keycloak/issues/30351
- [ ] https://github.com/keycloak/keycloak/issues/30855
- [x] Decide if it is enabled by default or not once it is fully supported - let's assume "yes"
- [x] Release note once it is fully supported
- [ ] https://github.com/keycloak/keycloak/issues/29505
- [ ] https://github.com/keycloak/keycloak/issues/32577
- [ ] https://github.com/keycloak/keycloak/issues/31115
- [ ] https://github.com/keycloak/keycloak/issues/31296
- [ ] https://github.com/keycloak/keycloak/issues/31760
- [ ] https://github.com/keycloak/keycloak/issues/32265
- [ ] https://github.com/keycloak/keycloak/issues/32387
```

```[tasklist]
### Optional Tasks
- [ ] https://github.com/keycloak/keycloak/issues/32582
- [ ] https://github.com/keycloak/keycloak/issues/32583
- [ ] https://github.com/keycloak/keycloak/issues/28418
```

**Comment by ahus1** [comment]
For all those watching this: There is now a GitHub discussion to capture user feedback, and provide additional information on how to try it out using the nightly releases: #28271

**Comment by istvano** [comment]
Hi @ahus1 
I am not sure if this was requested but if we are moving the sessions to the DB, I am also sure we need to build some sort of clean up as well. Would it be possible to add an Keycloak EVENT as well to keep track of which sessions have been removed so that we can keep track of them using external CIAM or scripts?

**Comment by ahus1** [comment]
@istvano - it hasn't been requested to create events for this. A cleanup that deletes those entries already exists, but it is a simple delete from the database. 

The events would be an enhancement. 

Please search the existing issues, and if none exists create an enhancement issue. The issue should contain a list of all the details the new event should contain, and you also might suggest a name for it. 

To prioritize the issue, it would be good to describe the scenarios where this is helpful. Just sending those events to another system is IMHO only means to an end that you didn't describe in your comment above, yet. With that end in mind, prioritization is then a simpler task, and is more likely to get the results you want to see. 

Then post the issue number here. I'll then add it to the tasks above. 

It might not be part of the first implementation, but let's see.

**Comment by ahus1** [comment]
The now default and only configuration is run this with caching only, so I removed the comparison of with and without from the optional tasks.

**Comment by ahus1** [comment]
Dropped for now from optional tasks: 

* Bundling session updates in on database transaction (user+client session, offline+online sessions) - too much effort and high risk
* Simplify offline_client_session table client id storing for external clients - too much migration of existing data
* Future idea: Use only one JPA transaction for both the main resource changes during login/logout/refresh and then writing the change to the database (current writing is done in afterCompletion phase) - this won't work with retries
* Rework caching and make the DB the source of truth (invalidation caches) + revisit idle and maxlifetime when doing so (only refresh should prolong session?) - out of scope for KC26
* When migrating sessions, print an estimated number of sessions to migrate at the start - no longer migrating sessions in KC26. 
* When searching for a list of sessions, don’t put them into the cache to avoid eviction of too many other session - let's wait if that is really necessary

**Comment by ahus1** [comment]
Main tasks are completed for this issue, therefore I'm closing this issue. Other optional tasks might continue later.

Thank you to everyone who put work into this for analyzing, implementing and testing this!
