### ISSUE TITLE
External Infinispan Deployments

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#28745]
### Description

In the context of multi-site high availability deployment, this issue suggests the removal of the embedded clustered caches and using the required external Infinispan server in cross-site mode only.

This is a requirement for Active-Active deployments.

### Motivation

Keeping the embedded clustered caches in sync with the external Infinispan is not simple. The current solution relies on events streaming to asynchronously update the embedded caches in both sites (sessions mostly) which is costly. Parts of the code also require all sessions to be available in the embedded caches and not fetch any updated value from external Infinispan (search for `SKIP_CACHE_LOAD` flag). 

To simplify the architecture and Keycloak source code, the proposal is to remove those embedded cache. 

The drawback focuses mainly on performance:
* Reads had a `num_owners / number of Keycloak servers` of finding the data locally and avoiding any network call. With the external Infinispan, a remote call is required (except if near-caching is enabled)
* Search and iteration are slower since all dataset is streamed to the Keycloak node. This will be improved in the future by using Infinispan Protostream marshaling and Queries.

There are benefits from this approach too. Besides the simplified source code, write operations would be faster since only the external Infinispan replicates data. Keycloak will be stateless, improving the startup times and, if possible by Keycloak logic, allowing different Keycloak versions to participate. Finally, upgrading Keycloak does not lose the sessions stored in the external Infinispan.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/28140
- [ ] https://github.com/keycloak/keycloak/issues/28648
- [ ] https://github.com/keycloak/keycloak/issues/28750
- [ ] https://github.com/keycloak/keycloak/issues/28751
- [ ] https://github.com/keycloak/keycloak/issues/28752
- [ ] https://github.com/keycloak/keycloak/issues/29135
- [ ] https://github.com/keycloak/keycloak/issues/28754
- [ ] https://github.com/keycloak/keycloak/issues/28755
- [ ] https://github.com/keycloak/keycloak/issues/29137
- [ ] https://github.com/keycloak/keycloak/issues/29394
```

**Comment by sventorben** [comment]
Quick question: Does this imply that also single-site deployments with multiple instances would need to set up an external infinispan instance/cluster to be able to operate or will all data be shared via the database in such a scenario?

**Comment by pruivo** [comment]
> Quick question: Does this imply that also single-site deployments with multiple instances would need to set up an external infinispan instance/cluster to be able to operate or will all data be shared via the database in such a scenario?

@sventorben It doesn't. 
The single-site deployment will use the database but, the users may choose to use an external Infinispan if they want to make the Keycloak nodes stateless (for example, for auto-scaling deployments).

**Comment by u2bo** [comment]
Do you support the keycloak  which  3-node cluster Pods to two k8s clusters and uses fixed IP addresses for communication?

**Comment by pruivo** [comment]
> Do you support the keycloak which 3-node cluster Pods to two k8s clusters and uses fixed IP addresses for communication?

Yes. It is mostly transparent for the Keycloak side but, the external Infinispan needs to be configured with cross-site enabled. A single external Infinispan shared between the Keycloak cluster also works, but it will be a single point of failure. 



> Does the keycloak operator support Infinispan high availability deployment only? How can I change the support if I am using k8s sts?

You need to configure the trust store because Keycloak uses TLS to communicate with the external Infinispan. Then, configure the credentials for access, as described in the [documentation](https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispanl), converting the Keycloak Operator option into the stateful set environment variables.

For the external Infinispan, you need to install the Infinispan operator [as documented here](https://infinispan.org/docs/infinispan-operator/main/operator.html#setting-up-xsite)

**Comment by u2bo** [comment]
> > Do you support the keycloak which 3-node cluster Pods to two k8s clusters and uses fixed IP addresses for communication?
> 
> Yes. It is mostly transparent for the Keycloak side but, the external Infinispan needs to be configured with cross-site enabled. A single external Infinispan shared between the Keycloak cluster also works, but it will be a single point of failure.
> 
> > Does the keycloak operator support Infinispan high availability deployment only? How can I change the support if I am using k8s sts?
> 
> You need to configure the trust store because Keycloak uses TLS to communicate with the external Infinispan. Then, configure the credentials for access, as described in the [documentation](https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispanl), converting the Keycloak Operator option into the stateful set environment variables.
> 
> For the external Infinispan, you need to install the Infinispan operator [as documented here](https://infinispan.org/docs/infinispan-operator/main/operator.html#setting-up-xsite)

i used it and config but not ready!  lost some config?
the keycloak log
`
2024-05-29 06:23:55,759 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) example-kc-0-62364: no members discovered after 2002 ms: creating cluster as coordinator
2024-05-29 06:23:55,768 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [example-kc-0-62364|0] (1) [example-kc-0-62364]
2024-05-29 06:23:55,821 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `example-kc-0-62364`, physical addresses are `[100.122.31.237:7800]`
2024-05-29 06:23:55,830 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-05-29 06:24:10,351 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: example-kc-0-62364, Site name: null
2024-05-29 06:24:10,470 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
`

**Comment by pruivo** [comment]
@u2bo do you want to create a GitHub discussion and share your configuration and logs?

**Comment by u2bo** [comment]
> @u2bo do you want to create a GitHub discussion and share your configuration and logs?

[#29960 ](https://github.com/keycloak/keycloak/issues/29960)

**Comment by Arnaud-FELTZ** [comment]
Please do not neglect updating the documtation regarding this.
Deploying cross DC is quite usual by now and alot of existing documentation or links rely on Wildfly or broken tutorials.

**Comment by ahus1** [comment]
@Arnaud-FELTZ - thank you for commenting here. For the setups with an external Infinispan in Keycloak 24+25, there are docs which describe this step by step: https://www.keycloak.org/high-availability/introduction

Once we have the setup we describe here fully supported (hopefully earlier), we plan for a similar documentation. 

You mention "Deploying cross DC is quite usual by now" ... at the same time I get comments that we didn't describe in our guides a stretched setup (no external Infinispan, but Keycloak nodes in different sites aka data centers). What you your thoughts on this?

**Comment by Arnaud-FELTZ** [comment]
@ahus1 : Precisely, I've gone all through all the links that are in this introduction and none explained how to setup Keycloak cross-DC with an external infinispan.

Almost every link in it have a prerequisite of using Kubernetes. Even the https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispan link that suggests that it can be in an agnostic way have as prerequesite to use Kubernetes.

A documentation that explain clearly how to link Keycloak / Infinispan w/o another technology prerequisite (Docker/Kubernetes/...) would be very welcome.
I've read dozen of differents threads this weekend about this and tried to set it up and wasn't able to set it up in less than 1d, that's too long for something that should be very straightforward and clearly documented.

**Comment by pruivo** [comment]
> Almost every link in it have a prerequisite of using Kubernetes. Even the https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispan link that suggests that it can be done in an agnostic way is misleading as it have as prerequesite : Kubernetes.

Did you scroll down or stop reading at the prerequisite? It is clear the options name for the CR and, if it isn't, there is a table at the end for the CLI options for the non-kubernetes environment. 

The most complex things to setup are the cross-site connection for Infinispan and the TLS certificates (assuming you want the communication between Keycloak and Infinispan encrypted). Both of them are handled automatically by the Operators.

For cross-site connection, check the [Cross Site Documentation](https://infinispan.org/docs/stable/titles/xsite/xsite.html#cross-site-replication). If you need help, please create a discussion and ping me.

I lack expertise in setting up certificates but it is described [in this documentation page](https://infinispan.org/docs/stable/titles/server/server.html#configuring-encryption). Feel free to ping me and I'll try to help you out.

**Comment by ahus1** [comment]
Feature wise, this is now complete. Thank you for all the work here! We're looking forward to a slimmer Keycloak deployment in KC26!

**Comment by oussamatahiri-lm** [comment]
Hello,

I have two Keycloak 22 containers running with embedded Infinispan without any issues in my local environment using Docker Compose. However, when I try to add a third Keycloak 22 container connected to an external Infinispan instance, I encounter problems during the launch of the third container.

Is it possible to configure this setup? Specifically, can I have two Keycloak instances with embedded caching and add a new one with external caching, while ensuring that all three containers synchronize their caches?

Thank you!

**Comment by pruivo** [comment]
@ot-lm At the Infinispan project, we don't support or test asymmetric configuration. So, I'm not surprised that it doesn't work. 

What's the use case for such a deployment and what is the error?

**Comment by pruivo** [comment]
It isn't possible with Keycloak. 

In theory, you could write a small program to connect to the Keycloak caches, read them, and store the data in an external Infinispan cluster. 

Keycloak 25 supports persistent sessions; the sessions are stored in the Database. 
See https://www.keycloak.org/2024/06/persistent-user-sessions-in-preview.html
It could migrate from the external Infinispan cluster.

As a side note, this feature is not available yet. It will be available in Keycloak 26 to support the multi-site use case.
