### ISSUE TITLE
Remove remaining deprecated Keycloak java adapters

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28774]
### Description

This task is about remove deprecated Keycloak java adapters, which were scheduled for the deprecation in Keycloak 24 (See https://www.keycloak.org/2024/03/keycloak-2400-released and the section **Java adapter deprecation and removal** .

This task is about both OIDC and SAML Java adapters, which were deprecated.

What we keep is just this (copy/pasting from the blog mentioned above):

```
The generic Authorization Client library will continue to be supported, and aims to be used in combination with any other OAuth 2.0 or OpenID Connect libraries.

The only adapter we will continue to deliver is the SAML adapter for latest releases of WildFly and EAP 8.x. Reasoning for continuing to support this is down to the fact that the majority of the SAML codebase in Keycloak was a contribution from WildFly. As part of this contribution we agreed to maintain SAML adapters for WildFly and EAP in the long run.
```

Other things we keep are also admin-client and client-registration-client (and related CLI). Pretty much the stuff in the Keycloak codebase inside directory `integration` is kept.

We need to:

- Remove affected adapters from "Download" page - https://www.keycloak.org/downloads

- Make sure they are not tested in adapter pipelines (will need to check with QA team)

- Remove from Keycloak codebase (including updates in the distribution)

- Remove from documentation (especially we can probably remove this whole section for OIDC https://www.keycloak.org/docs/latest/securing_apps/index.html#keycloak-java-adapters . For SAML, we likely cannot remove this whole section https://www.keycloak.org/docs/latest/securing_apps/index.html#using-saml-to-secure-applications-and-services as AFAIK EAP/Wildfly documentation rely on some parts of our documentation (should be doublechecked), but some parts of it can be removed)

- Doublecheck quickstarts (but AFAIK they already don't depend on java adapters)

- Update documentation (release notes, upgrading guide, removing stuff from securing-apps guide, doublecheck other guides possibly referencing Keycloak adapters). We can also doublecheck if we find good alternatives to Keycloak adapters, which we can reference from our documentation (Feedback from the community would be welcome on this issue, so if anyone from the community is already successfully using alternatives to some deprecated Keycloak Java adapters, please write the comment on this issue as this might be useful reference)

- Doublecheck GH labels (especially all of those used on this epic :-) )

- Doublecheck server codebase (lower priority): Can we remove some server functionality, which was used solely by Keycloak Java adapters and was specific to Keycloak (not OIDC, SAML specs compliant) ? Some ideas are:
  - Some functionality by `ResourceAdminManager` , which is used by Keycloak server to update adapters about some event. Those are mostly Keycloak specific and not based on OIDC specs (like Push not-before, Push login-all, test availability of adapter cluster nodes etc). On the other hand, this might be used by Elytron OIDC adapter and hence cannot be removed
  - Export adapter configs (Go to some client in admin console, right top corner `actions` and click `Download adaptor config` . There are 3 options for downloading adapter configs. Maybe some (or all?) of them can be removed, but we should again doublecheck if they are NOT used by Elytron OIDC Wildfly adapter
  - The `AdapterInstallationClientRegistrationProvider` (should again doublecheck if needed by Elytron OIDC Wildfly adapter)
  - If we cannot remove the things above, we should doublecheck if they are still tested once we remove adapter tests. As it is possible, that some of this server-functionality was tested just as part of the adapter tests. However I see for instance `TestApplicationResourceProviderFactory` class indicates that we test the stuff from above.

### Discussion

https://github.com/keycloak/keycloak/discussions/categories/adapter-deprecation?discussions_q=is%3Aopen+adapter+deprecation+category%3A%22Adapter+deprecation%22

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/28776
- [ ] https://github.com/keycloak/keycloak/issues/28777
- [ ] #23381
- [ ] https://github.com/keycloak/keycloak/issues/29225
- [ ] https://github.com/keycloak/keycloak/issues/28778
- [ ] https://github.com/keycloak/keycloak/issues/28779
- [ ] https://github.com/keycloak/keycloak/issues/28780
- [ ] https://github.com/keycloak/keycloak/issues/28781
- [ ] https://github.com/keycloak/keycloak/issues/28782
- [ ] https://github.com/keycloak/keycloak/issues/28783
- [ ] https://github.com/keycloak/keycloak/issues/28784
- [ ] https://github.com/keycloak/keycloak/issues/28785
- [ ] https://github.com/keycloak/keycloak/issues/28786
- [ ] https://github.com/keycloak/keycloak/issues/29089
- [ ] https://github.com/keycloak/keycloak/issues/28787
- [ ] https://github.com/keycloak/keycloak/issues/28788
- [ ] https://github.com/keycloak/keycloak/issues/28789
- [ ] https://github.com/keycloak/keycloak/issues/28790
- [ ] https://github.com/keycloak/keycloak/issues/28792
- [ ] https://github.com/keycloak/keycloak/issues/29189
- [ ] https://github.com/keycloak/keycloak/issues/28791
- [ ] https://github.com/keycloak/keycloak/issues/29970
- [ ] https://github.com/keycloak/keycloak/issues/29882
- [ ] https://github.com/keycloak/keycloak/issues/28794
- [ ] https://github.com/keycloak/keycloak/issues/29104
- [ ] https://github.com/keycloak/keycloak/issues/29912
- [ ] https://github.com/keycloak/keycloak/issues/29922
- [ ] https://github.com/keycloak/keycloak/issues/30347
- [ ] https://github.com/keycloak/keycloak/issues/30324
- [ ] https://github.com/keycloak/keycloak/issues/30553
- [ ] https://github.com/keycloak/keycloak/issues/30554
- [ ] https://github.com/keycloak/keycloak/issues/30555
- [ ] https://github.com/keycloak/keycloak/issues/30556
- [ ] https://github.com/keycloak/keycloak/issues/28795
```

**Comment by mposolda** [comment]
All subtasks done. Closing. We can have separate follow-up issues if something more is considered to be cleaned.
