### ISSUE TITLE
Doublecheck testsuite after adapters removal

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28795]
Remaining cleanup of the testsuite after adapters are removed. This depends on removing adapters from the pipeline: https://github.com/keycloak/keycloak/issues/28777 .

Some possibilities of what can be removed:
- Probably everything under `testsuite/integration-arquillian/servers/app-server`
- Various stuff from `pom.xml` files or `arquillian.xml` referencing app servers
- Adapter pages (maybe whole package `org.keycloak.testsuite.adapter.page` from base testsuite from `src/main/java`)
- Maybe whole package `org.keycloak.testsuite.adapter` from base testsuite from `src/test/java`
- Various helper utilities (like annotation `@AppServerContainer` or constants from the class `ContainerConstants`

This issue may be split into multiple tasks to iteratively cleanup the various things.

```[tasklist]
### Child tasks
- [ ] #30553
- [ ] #30554
- [x] https://github.com/keycloak/keycloak/issues/30867
- [ ] https://github.com/keycloak/keycloak/issues/30869
- [ ] https://github.com/keycloak/keycloak/issues/30870
- [ ] https://github.com/keycloak/keycloak/issues/30871
```

**Comment by mposolda** [comment]
@douglaspalmer @rmartinc FYI. There are related tasks #30554 and #30553 . Added them as childs of this one
