### ISSUE TITLE
Scalability of Groups

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#30085]
## Goals

We need to make sure Keycloak will scale to thousands of groups. As a starting point, our goal is to:

* **Authentication**
  * Log-in is not drastically impacted by at least 10k organizations in a realm so that a log-in attempt and the rendering pages are not so different than when not using organizations
  * Log-in is not drastically impacted by at least 10k organizations in a realm where there are 10k realm groups so that a log-in attempt and rendering pages are not so different than when not using organizations

* **Authorization**
  * Fine-grained Admin Permissions not drastically impacted by 10k organizations in a realm when enforcing access on the administrator group membership
  * Fine-grained Admin Permissions not drastically impacted by 10k organizations in a realm where there are 10k realm groups when enforcing access on the administrator group membership

* **Token**
  * Issuing tokens is not drastically impacted by at least 10k organizations in a realm where there are 10k realm groups and groups are mapped into tokens
  * Issuing tokens is not drastically impacted by at least 10k organizations in a realm and organizations are mapped into tokens

* **Admin API/UI**
  * Admin API/UI not drastically impacted by at least 10k realm groups when managing groups
  * Admin API/UI not drastically impacted by at least 10k realm groups when managing organizations
  * Admin API/UI not drastically impacted by at least 10k organizations in a realm when managing groups
  * Admin API/UI not drastically impacted by at least 10k organizations in a realm when managing organizations

* **Testing**
  * Extend the `keycloak-benchmark` tool dataset provider to create organizations and groups in a realm for testing to make it easier to reproduce performance issues in the future

Each realm group must have at least 1k subgroups.

## Tasks

- [x] #30589
- [x] #30634
- [x] #31056
- [x] https://issues.redhat.com/browse/ISPN-16267
- [x] Review caching of groups to make sure the responses from operations currently being cached are healthy and invalidating entries accordingly
- [x] Review database indexes that can be added or change to improve database query executions
- [x] Remove organizations and groups using a query when deleting a realm

**Comment by pedroigor** [comment]
A suggestion how to approach this one:

* Create a dataset in keycloak-benchmark tool to be able to load the database with a X number of groups in a realm
* Create a dataset in keycloak-benchmark tool to be able to load the database with a X number of organizations in a realm
* Evaluate responses from the Admin API when managing groups, mainly the listing and pagination
* Evaluate responses from the Admin API when managing organizations, mainly the listing and pagination
