### ISSUE TITLE
Internal error occurs for the removed flow which override by the client

### ISSUE THREAD

**Issue by lexcao** [keycloak/keycloak#30706]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When I try login with the client that has setup override authentication flow but the flow was removed, there is an internal error with following logs.
```
2024-06-25 00:25:48,272 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: org.keycloak.models.ModelException: Client account-console has browser flow override, but this flow does not exist
	at org.keycloak.models.utils.AuthenticationFlowResolver.resolveBrowserFlow(AuthenticationFlowResolver.java:38)
	at org.keycloak.protocol.AuthorizationEndpointBase.getAuthenticationFlow(AuthorizationEndpointBase.java:160)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:107)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:341)
```

And back to the Admin UI of the client shows the **blank** setting for the override flow
<img width="720" alt="image" src="https://github.com/keycloak/keycloak/assets/14901139/bff232c7-72c0-4d6c-b458-37def32c7fc9">

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

There are two improvements we can add:
1. prevent deleting the flow when used by client flow overrides
2. fallback to the default flow (browser) when the flow is missing.

### Actual behavior

Internal error occurs for the user and the administrator is not aware for this as well.

### How to Reproduce?

1. Duplicate a browser flow `Copy of browser`
2. Set a browser flow override to flow `Copy of browser` for client `account-console`
3. Remove the flow `Copy of browser`
4. Go to `account-console` page trying to login
5. The error occurs

### Anything else?

I think it is same to the issue https://github.com/keycloak/keycloak/issues/20193.
And related to issue https://github.com/keycloak/keycloak/issues/9394 as well.

I think we can split the improvements into to parts:

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/30707
- [ ] https://github.com/keycloak/keycloak/issues/30765
```

**Comment by graziang** [comment]
@lexcao It seems like a valid issue even with two duplicates. Let me know if you or someone else wants to fix it; otherwise, I'll do it in the next few days.

**Comment by lexcao** [comment]
Hi @graziang 
Thanks for confirming.
I am on it.

**Comment by mposolda** [comment]
@lexcao Closing now as both subtasks are closed. Feel free to re-open if there is still something missing.
