### ISSUE TITLE
Move keycloak client libs into separate repository

### ISSUE THREAD

**Issue by pskopek** [keycloak/keycloak#30787]
### Description

Following Keycloak artifacts needs a separate repository and no dependency on Quarkus:
- org.keycloak:keycloak-admin-client
- org.keycloak:keycloak-authz-client
- org.keycloak:keycloak-policy-enforcer

The dedicated repository already created https://github.com/keycloak/keycloak-client 

We need to be able to release these artifacts independently of the Keycloak server release. 

Ideally, the artifacts should not have any dependency on artifacts from `keycloak` repository (with the exception of the testsuite in `keycloak-client` repository, which probably can have a dependency on `keycloak` repository to be able to consume and run Keycloak server) and similarly `keycloak` repository should not have any dependency on those.

Because `keycloak` repository still need to use some of those artifacts in it's testsuite (like `keycloak-admin-client` and probably also `keycloak-authz-client`), it is possible that we may need to keep Java classes in the `keycloak` repository and have some mechanism for copying/syncing Java classes from `keycloak` repository to the `keycloak-client` repository.

Some of the modules can be possibly directly moved to the separate repository as they are not used in much Keycloak tests, so the corresponding tests can be moved as well to client repository (maybe policy-enforcer, but this is to be investigated).

#### Optional targets

Handle also those artifacts to separate repository:
- org.keycloak:keycloak-client-registration-api
- Keycloak SAML adapter

But those are not needed by Quarkus and hence don't have so much priority

### Motivation

Cyclic dependency on Quarkus needs to be broken.
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/30796
- [ ] https://github.com/keycloak/keycloak/issues/30798
- [ ] https://github.com/keycloak/keycloak/issues/30799
- [x] https://github.com/keycloak/keycloak/issues/30800
- [ ] https://github.com/keycloak/keycloak/issues/30805
- [ ] https://github.com/keycloak/keycloak/issues/30807
- [ ] https://github.com/keycloak/keycloak/issues/31261
- [ ] https://github.com/keycloak/keycloak/issues/31262
- [ ] https://github.com/keycloak/keycloak/issues/30927
- [ ] https://github.com/keycloak/keycloak/issues/31263
- [ ] https://github.com/keycloak/keycloak/issues/30926
- [ ] https://github.com/keycloak/keycloak/issues/31264
- [ ] https://github.com/keycloak/keycloak/issues/31443
- [ ] https://github.com/keycloak/keycloak/issues/30819
- [x] https://github.com/keycloak/keycloak/issues/30817
- [ ] https://github.com/keycloak/keycloak/issues/32025
- [ ] https://github.com/keycloak/keycloak/issues/31978
- [ ] https://github.com/keycloak/keycloak/issues/31870
- [ ] https://github.com/keycloak/keycloak/issues/32099
- [ ] https://github.com/keycloak/keycloak/issues/31372
- [ ] https://github.com/keycloak/keycloak/issues/31384
- [ ] https://github.com/keycloak/keycloak/issues/31653
- [ ] https://github.com/keycloak/keycloak/issues/30804
- [ ] https://github.com/keycloak/keycloak/issues/30803
- [ ] https://github.com/keycloak/keycloak-client/issues/15
- [ ] https://github.com/keycloak/keycloak-client/issues/51
- [ ] https://github.com/keycloak/keycloak/issues/30806
- [x] https://github.com/keycloak/keycloak/issues/30818
- [ ] https://github.com/keycloak/keycloak-client/issues/34
- [ ] https://github.com/keycloak/keycloak-client/issues/38
- [x] https://github.com/keycloak/keycloak/issues/30815
- [ ] https://github.com/keycloak/keycloak-client/issues/46
- [ ] https://github.com/keycloak/keycloak/issues/33050
- [ ] https://github.com/keycloak/keycloak/issues/32644
- [ ] https://github.com/keycloak/keycloak/issues/33899
- [ ] https://github.com/keycloak/keycloak/issues/33901
- [ ] https://github.com/keycloak/keycloak/issues/32962
- [ ] https://github.com/keycloak/keycloak-client/issues/26
- [ ] https://github.com/keycloak/keycloak-client/issues/86
- [ ] https://github.com/keycloak/keycloak-client/issues/92
- [ ] https://github.com/keycloak/keycloak-web/issues/524
- [ ] https://github.com/keycloak/keycloak/issues/34666
- [ ] https://github.com/keycloak/keycloak-client/issues/101
- [ ] https://github.com/keycloak/keycloak-client/issues/87
- [ ] https://github.com/keycloak/keycloak-client/issues/93
- [ ] https://github.com/keycloak/keycloak-client/issues/90
- [ ] https://github.com/keycloak/keycloak/issues/34949
- [ ] https://github.com/keycloak/keycloak/issues/31383
- [ ] https://github.com/keycloak/keycloak/issues/35433
- [ ] https://github.com/quarkusio/quarkus/issues/43259
- [ ] https://github.com/keycloak/keycloak-web/issues/528
```

**Comment by mposolda** [comment]
Closing the epic as the "core" work was done and node.js adapter is decoupled from Keycloak release cycle. Moving remaining task https://github.com/keycloak/keycloak-web/issues/528 for announcements of keycloak-web out of this epic and handling it as a separate issue.
