### ISSUE TITLE
 Active/Active x-site Infinispan and loadbalancer handling

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#30971]
### Description

To handle an active-active setup, Keycloak needs an update loadbalancer based on the global accelerator and operational procedures to handle this.  

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/29303
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/876
- [ ] https://github.com/keycloak/keycloak/issues/31029
- [x] Consider deprecating the A/P guide in favor of the new A/A guide, outlining why the new setup is simpler to operate (for example not using Route 53 DNS based failover any more)
- [ ] https://github.com/keycloak/keycloak/issues/31837
- [ ] https://github.com/keycloak/keycloak/issues/32343
```

**Comment by ahus1** [comment]
All items in this epic are now complete, closing!
