### ISSUE TITLE
Convert securing-applications documentation to guide format

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31324]
Convert current [Securing application and services documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html) into the [Guide format](https://www.keycloak.org/guides) similarly like was done for "Server Installation guide" some time ago. There is already section Securing applications on the [guide page](https://www.keycloak.org/guides). So maybe we can just add new pages to that section converted from [current "Securing application" documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html)?
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31328
- [ ] https://github.com/keycloak/keycloak/issues/31329
- [ ] https://github.com/keycloak/keycloak/issues/31330
- [ ] https://github.com/keycloak/keycloak/issues/31331
- [ ] https://github.com/keycloak/keycloak/issues/31332
- [ ] https://github.com/keycloak/keycloak/issues/31333
- [ ] https://github.com/keycloak/keycloak/issues/31334
- [ ] https://github.com/keycloak/keycloak/issues/31569
- [ ] https://github.com/keycloak/keycloak/issues/31695
- [ ] https://github.com/keycloak/keycloak/issues/31696
- [ ] #31697
```

**Comment by graziang** [comment]
@mposolda here the three new tasks to add:

- https://github.com/keycloak/keycloak/issues/31695
- https://github.com/keycloak/keycloak/issues/31696
- https://github.com/keycloak/keycloak/issues/31697

Thanks!

**Comment by mposolda** [comment]
Closing as all the subtasks are finished. The "Securing Applications" documentation is fully migrated into the guides.
