### ISSUE TITLE
Can we remove deprecated Node.JS adapter?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31326]
### Tasks

- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/451
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/452
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/453
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/454
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/455
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/456

**Comment by Zysberg** [comment]
What will be the alternative after removing the NodeJS adapter?
