### ISSUE TITLE
Update quickstarts according to keycloak-client repository changes

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31383]
Keycloak quickstarts have lots of references to `keycloak-admin-client`, `keycloak-authz-client` and `keycloak-policy-enforcer`, which were all moved to [keycloak-client repository](https://github.com/keycloak/keycloak-client) . The quickstarts will need to be updated according to this. Some of the quickstarts (especially extension quickstarts, but also operator and UI quickstarts) have references to `keycloak` artifacts when some others (especially spring and Jakarta quickstarts) have references especially to `keycloak-client` artifacts.

Some items discussed with @stianst (for the reference) regarding how quickstarts can work:

- Keycloak-quickstarts branch `main` can have reference to `keycloak` snapshot version and also to `keycloak-client` snapshot version. This is already done during #31416 and is done here: https://github.com/keycloak/keycloak-quickstarts/blob/main/pom.xml#L38-L39 .

- The branch `latest` of quickstarts will need to be updated during every release of `keycloak-client` or `keycloak` with the currently released version of `keycloak` or `keycloak-client` 
 
- The tag for quickstarts will be created during every release of `keycloak` server as is done today. It is created from `latest` branch, so should contain also reference to last released `keycloak-client` 

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31416
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/583
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/584
- [ ] https://github.com/keycloak/keycloak/issues/31417
```

**Comment by mposolda** [comment]
Updated to `needs-discussion` as we discussed some ideas for simplify quickstarts (Removing branch `latest` and keeping just the branch `main` pointing to last released version of keycloak-server and client).

**Comment by mposolda** [comment]
We had the discussion about quickstarts within the wider team. The approach, which we are going to use is the following:

- In quickstarts, we won't have anymore branch `latest`. We will have just the branch `main`. This will be also the default branch

- The `main` branch of quickstarts won't have references to snapshot versions of keycloak and keycloak-client. Instead, it will have references to last released version of keycloak server and last released version of keycloak-client. In other words, those lines will be always set to last released version of keycloak server and keycloak-client (Keycloak-client was already updated yesterday by Stian to last released version 26.0.2): https://github.com/keycloak/keycloak-quickstarts/blob/main/pom.xml#L38-L39

- During the release of keycloak server, it will update just this one line in main branch in `pom.xml` with the server version. Similarly for the release of keycloak-client.

- There won't be tags for community quickstarts (looks that nobody using them anyway)

- Sending PRs: The proposal above means that if people are sending PRs to quickstarts, they will need to do quickstart examples which work with the last released version of server and client. So for example if you want to add quickstart for some new feature, which is going to be developed in 26.1.0, it means that this quickstart can be merged to `main` branch after the Keycloak server 26.1.0 is released. It cannot be merged before though due the server version in `pom.xml` is pointing to last released version (which is not 26.1.0, but some older like 26.0.X). 


----------------------------------------------------------


The tasks needed to achieve this are:

- Update `main` branch to reference last released keycloak server (`26.0.5`) instead of `snapshot` version

- Make `main` branch the default branch of quickstarts and remove `latest` branch entirely

- Update various README files, which are referring to the `latest` branch (At least `README.md`, `CONTRIBUTING.md` and `pull_request_template.md` from the root directory. Not sure if some README inside individual submodules need some update as well (maybe not...)

- Update release process of keycloak server. We won't create tag and we won't create `latest` branch from the current `main` branch. Instead we will simply just upate the server version to the currently released keycloak server - so just this single line in the `main` branch with `version.keycloak` property is going to be updated: https://github.com/keycloak/keycloak-quickstarts/blob/main/pom.xml#L38 . I am not sure if we want some workflow inside quickstart repository or if we can use the existing mechanism (which is probably done somewhere in the release repository?)

- Create GH workflow in quickstarts, which will test quickstarts with the latest Keycloak server nightly version. This is to avoid negative surprise when we want to release keycloak server major/minor version (For example Keycloak 26.1.0) and we suddenly figure that quickstarts don't work at all with the currently released server. This is similar to this task related to keycloak-client: https://github.com/keycloak/keycloak-client/issues/87

**Comment by mposolda** [comment]
Closing as the tasks from previous comment moved to dedicated task https://github.com/keycloak/keycloak/issues/35433
