### ISSUE TITLE
Support for standard Token-Exchange

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#31546]
### Description

This epic describes all necessary issues to make token-exchange fully supported.

### Discussion

https://github.com/keycloak/keycloak/discussions/26502

### Issues

[All issues](https://github.com/keycloak/keycloak/labels/area%2Ftoken-exchange) in `area/token-exchange` should be reviewed and moved to corresponding tasks

### Motivation

Keycloak has had the [OAuth RFC 8693: Token Exchange](https://oauth.net/2/token-exchange/) feature for many years; however, since its inception, it has remained a technology preview feature. Following many requests from the community and customers, the Keycloak team is committed to getting token exchange out of preview.

### Scope of the work

The initial scope is to have support for internal/internal token exchange. We might have follow-up epics for support other use-cases (like external to internal, internal to external, impersonation use-cases like direct naked impersonation etc).

## Standard token exchange

These are tasks to make sure that Keycloak is compliant with the [token exchange specification](https://datatracker.ietf.org/doc/html/rfc8693), which is in current Keycloak documentation referred as [internal to internal token exchange](https://www.keycloak.org/securing-apps/token-exchange#_internal-token-to-internal-token-exchange). Also here are tasks to make sure that internal-internal token exchange could be supported by default. Which means:
- Good documentation and testing coverage
- Threat modeling and security (including the fine grained control over what is permitted or not) 
- Fixing/implement some fundamental gaps in the current implementation.

### Required for supported token-exchange

This tasklist contains tasks, which are minimum needed for supported standard token-exchange. So far, it is planned to implement them asap (ideally Keycloak 26.2). The "optional" tasks are not included here.

See [this document](https://docs.google.com/document/d/16Ug7tHDq3EAZHv0PaBVe4OQ4poTDHbaXoGbkXQtO2iI/edit) for the discussions and context about the tasks for standard token-exchange for Keycloak 26.2

```[tasklist]
- [ ] https://github.com/keycloak/keycloak/issues/31547
- [ ] https://github.com/keycloak/keycloak/issues/31548
- [ ] https://github.com/keycloak/keycloak/issues/31550
- [ ] https://github.com/keycloak/keycloak/issues/35504
- [ ] https://github.com/keycloak/keycloak/issues/35506
- [ ] https://github.com/keycloak/keycloak/issues/35505
- [ ] https://github.com/keycloak/keycloak/issues/37104
- [ ] https://github.com/keycloak/keycloak/issues/37105
- [ ] https://github.com/keycloak/keycloak/issues/37108
- [ ] https://github.com/keycloak/keycloak/issues/37109
- [ ] https://github.com/keycloak/keycloak/issues/37111
- [ ] https://github.com/keycloak/keycloak/issues/37147
- [ ] https://github.com/keycloak/keycloak/issues/37113
- [ ] https://github.com/keycloak/keycloak/issues/37112
- [ ] https://github.com/keycloak/keycloak/issues/37114
- [ ] https://github.com/keycloak/keycloak/issues/37121
- [ ] https://github.com/keycloak/keycloak/issues/37110
- [ ] https://github.com/keycloak/keycloak/issues/37552
- [ ] https://github.com/keycloak/keycloak/issues/37115
- [ ] https://github.com/keycloak/keycloak/issues/37554
- [ ] https://github.com/keycloak/keycloak/issues/37118
- [ ] https://github.com/keycloak/keycloak/issues/37122
- [ ] https://github.com/keycloak/keycloak/issues/37123
- [ ] https://github.com/keycloak/keycloak/issues/37124
- [ ] https://github.com/keycloak/keycloak/issues/37116
- [ ] https://github.com/keycloak/keycloak/issues/37117
- [ ] https://github.com/keycloak/keycloak/issues/37119
- [ ] https://github.com/keycloak/keycloak/issues/37693
- [ ] https://github.com/keycloak/keycloak/issues/37367
- [ ] https://github.com/keycloak/keycloak/issues/37120
- [ ] https://github.com/keycloak/keycloak/issues/37832
- [ ] https://github.com/keycloak/keycloak/issues/37126
- [ ] https://github.com/keycloak/keycloak/issues/37368
```

### Other issues related to standard token-exchange

This list contains tasks, enhancements and reported bugs, which are also related to standard token-exchange. ATM those are not considered "blockers" for supported standard token-exchange. After we finish the tasks from the list above, we may create follow-up epic and add the tasks from the list below to that epic. Before that, we may need to triage those again as:
- Some of those issues might be addressed by the other tasks from the list above. In this case, we can close them.
- Some of those issues might be addressed as a follow-ups (and hence should be moved to the new epic)
- Some of those issues might be addressed in a bit different way than described in the issue (due token-exchange refactoring). In this case, we can move them to the new epic with some updated description
- Some of those issues might be unsupported and hence we might close them as "won't do"

```[tasklist]
- [ ] https://github.com/keycloak/keycloak/issues/31553
- [ ] https://github.com/keycloak/keycloak/issues/36942
- [ ] https://github.com/keycloak/keycloak/issues/29614
- [ ] https://github.com/keycloak/keycloak/issues/17220
- [ ] https://github.com/keycloak/keycloak/issues/35507
- [ ] https://github.com/keycloak/keycloak/issues/23144
- [ ] https://github.com/keycloak/keycloak/issues/17008
- [ ] https://github.com/keycloak/keycloak/issues/31797
- [ ] https://github.com/keycloak/keycloak/issues/30358
- [ ] https://github.com/keycloak/keycloak/issues/33611
- [ ] https://github.com/keycloak/keycloak/issues/19148
- [ ] https://github.com/keycloak/keycloak/issues/33321
- [ ] https://github.com/keycloak/keycloak/issues/33252
- [ ] https://github.com/keycloak/keycloak/issues/20075
- [ ] https://github.com/keycloak/keycloak/issues/31552
- [ ] https://github.com/keycloak/keycloak/issues/33239
- [ ] https://github.com/keycloak/keycloak/issues/36870
- [ ] https://github.com/keycloak/keycloak/issues/38279
```

## Federated token exchange

Tasks related to [external-internal](https://www.keycloak.org/securing-apps/token-exchange#_external_token_to_internal_token_exchange) or [internal-external](https://www.keycloak.org/securing-apps/token-exchange#_internal_token_to_external_token_exchange) token exchange where integration with some IDP is involved.

Dedicated epic created for the federated-token exchange support: https://github.com/keycloak/keycloak/issues/38335

## Impersonation

Dedicated epic created for the subject-impersonation support: https://github.com/keycloak/keycloak/issues/38336

**Comment by antikalk** [comment]
Would it make sense to add this issue: [Allow for token-exchange with refresh-token of IDP](https://github.com/keycloak/keycloak/issues/29313) ? According to the spec you can do a token-exchange with a refresh-token when providing the refresh-token type. 

I have provided a PR with a possible solution, allowing the internal-to-external token-exchange with providing a refresh token.

**Comment by thomasdarimont** [comment]
Thanks @antikalk for the suggestion! That sounds reasonable to me, I added it to the list.

**Comment by francis-pouatcha** [comment]
Just for Information from today's breakout session: https://www.ietf.org/archive/id/draft-parecki-oauth-client-id-metadata-document-01.html

**Comment by cgeorgilakis** [comment]
I copy paste our opinion from the referenced discussion for some extra needed changes:

> Things we believe that should be changed :
> 
> - Remove consent request. There is no need for consent because token exchange is not a browser flow. We want clients executing token exchange to request consent in other OAuth flows.
> 
> - Move to (Token exchange) policies rules that decide if token exchange can be executed. In this way, each application can decide how strict it will be. For example, we do not want the rule ‘Without audience parameter, confidential clients can exchange if they are within the token audience or azp claim is this client id.’

We could provide PRs especially for the first one if you agree.

**Comment by thomasdarimont** [comment]
@cgeorgilakis that sounds great! Could you create an issue for the "Improved consent handling" you mentioned?

Regarding the token exchange / impersonation policies I think it would be good to discuss API proposals here:
https://github.com/keycloak/keycloak/issues/31552
If you already have some suggestions, feel free to post them :)

**Comment by francis-pouatcha** [comment]
@thomasdarimont can you please add this to the epic: https://github.com/keycloak/keycloak/issues/31797

**Comment by mcesar29** [comment]
@thomasdarimont  will the admin-fine-grained-authz feature also be released outside of preview?

I'm testing the token-exchange feature, and I can only use it if I enable the admin fine grained feature. Maybe I'm doing something wrong, but the documentation shows me a permissions tab in the client, which I can only see if admin fine grained is enabled.

**Comment by thomasdarimont** [comment]
Added issue: https://github.com/keycloak/keycloak/issues/34682

**Comment by thomasdarimont** [comment]
Thanks for your valuable feedback @mposolda! I like the idea of grouping the issues to enable more focussed development. I think it's fine to do it in this issue. 

What groups do you suggest? How about:
- Internal-to-Internal Token-Exchange
- External-to-Internal Token-Exchange
- Internal-to-External Token-Exchange
- Impersonation

**Comment by stianst** [comment]
> Thanks for your valuable feedback @mposolda! I like the idea of grouping the issues to enable more focussed development. I think it's fine to do it in this issue.
> 
> What groups do you suggest? How about:
> 
> * Internal-to-Internal Token-Exchange
> * External-to-Internal Token-Exchange
> * Internal-to-External Token-Exchange
> * Impersonation

* Standard token exchange 
* Federated token exchange
* Impersonation token exchange

**Comment by DenEwout** [comment]
Issues with regards to the validation of the typ header should be prioritized imho as a lot of external to internal token flows are broken now, depending on the IDP. Keycloak itself also uses "JWT" in its own typ header if I'm not mistaken.

See:
- https://github.com/keycloak/keycloak/issues/33332
- https://github.com/keycloak/keycloak/pull/35075 (Awaiting review)

**Comment by mposolda** [comment]
Closing the epic. Keycloak 26.2.0 will contain supported standard token-exchange. For now only internal-internal token-exchange is going to be supported when client exchanges the token, which was issued to another client in the same realm.

More details in the latest Keycloak nightly documentation, which is going to be also present in the Keycloak 26.2.0 documentation: https://www.keycloak.org/nightly/securing-apps/token-exchange .

We plan to continue on the token-exchange use-cases in the further Keycloak releases. Follow-up epics:
- https://github.com/keycloak/keycloak/issues/38335
- https://github.com/keycloak/keycloak/issues/40704
- https://github.com/keycloak/keycloak/issues/38336
- https://github.com/keycloak/keycloak/issues/38315

See also this filter for the further issues related to standard token-exchange, which we don't yet support (For example delegation, `resource` parameter support etc): https://github.com/keycloak/keycloak/issues?q=is%3Aissue%20state%3Aopen%20label%3Aarea%2Ftoken-exchange%2Fstandard .
