### ISSUE TITLE
Scalability of Identity Provider Mappers

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#31730]
### Description

Currently the identity provider mappers are managed through the `RealmModel`, and cached along with the realm data in `CachedRealm`. Any changes to the mappers (creation of a new mapper, removal of a mapper, update of an existing mapper) trigger a full realm invalidation, which forces the whole realm to be reloaded from the DB along with the list of IDP mappers, which can be pretty large and doesn't scale.

This epic tracks the work to decouple the mappers from the realm model, and manage them in cache independently from the realm.
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31731
- [ ] https://github.com/keycloak/keycloak/issues/31732
- [ ] https://github.com/keycloak/keycloak/issues/31733
- [ ] https://github.com/keycloak/keycloak/issues/31734
- [ ] https://github.com/keycloak/keycloak/issues/31735
- [ ] https://github.com/keycloak/keycloak/issues/31736
- [ ] https://github.com/keycloak/keycloak/issues/31738
```

**Comment by cgeorgilakis** [comment]
Nice. Mappers will be more than IdPs.
However, I believe no pagers are needed (5-10 max per IdP). The most important is to get fast mappers per IdP (needed in every broken login and admin ui).
