### ISSUE TITLE
Not possible to import realm with newest Java admin-client against Keycloak 24 

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#32025]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

Assuming that I use Java admin-client of latest Keycloak nightly and I am trying to import the realm to Keycloak 24.0.5 server with the admin-client call like:
```
RealmRepresentation realm = loadRealm(getClass().getResourceAsStream("/authorization-test/test-authz-realm.json"));
adminClient.realms().create(realm);
```

This will fail with the HTTP 400 error and with this exception on the server (can be seen just when debugging `RealmsAdminResource.importRealm` on the server) :

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class org.keycloak.representations.idm.ClientRepresentation), not marked as ignorable (43 known properties: "enabled", "clientAuthenticatorType", "redirectUris", "clientId", "authenticationFlowBindingOverrides", "authorizationServicesEnabled", "name", "implicitFlowEnabled", "registeredNodes", "nodeReRegistrationTimeout", "publicClient", "attributes", "protocol", "webOrigins", "protocolMappers", "id", "baseUrl", "surrogateAuthRequired", "adminUrl", "fullScopeAllowed", "frontchannelLogout", "clientTemplate", "origin", "defaultClientScopes", "directGrantsOnly", "rootUrl", "secret", "useTemplateMappers", "notBefore", "useTemplateScope", "standardFlowEnabled", "description", "directAccessGrantsEnabled", "alwaysDisplayInConsole", "useTemplateConfig", "serviceAccountsEnabled", "optionalClientScopes", "consentRequired", "access", "bearerOnly", "registrationAccessToken", "defaultRoles", "authorizationSettings"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 3693] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["clients"]->java.util.ArrayList[0]->org.keycloak.representations.idm.ClientRepresentation["type"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1153)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1793)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1771)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3883)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:94)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:79)
	at org.keycloak.storage.datastore.DefaultExportImportManager.importRealm(DefaultExportImportManager.java:156)
	... 12 more
```

The realm JSON file looks like this https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/test-authz-realm.json .

Note there is no field "type" on the client in the JSON file. And it is possible to import this JSON file in the admin console in Keycloak 24. Just the import with the admin-client does not work.

The field `type` was added to the `ClientRepresentation` object after Keycloak 24 release. So it is available in the `ClientRepresentation` on the admin-client side, but NOT in the `ClientRepresentation` on the server-side. When manually removing the field on the client-side, the similar exception happens due the field `organizationsEnabled` on `RealmRepresentation` (also added after Keycloak 24 release).

The Java admin-client currently converts `RealmRepresentation` (and other representations) into JSON with all the fields (like `organizationsEnabled`) being present with null values. This later causes the issue on the server due those fields are unknown.

### Version

admin-client nightly with Keycloak server 24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

It is possible to import realm with Java admin-client of latest version into Keycloak servers of older versions (like Keycloak server 24.0.5)

### Actual behavior

Import of the realm fails with Java admin-client of latest version into Keycloak servers of older versions (like Keycloak server 24.0.5)

### How to Reproduce?

See the description for more details.

### Anything else?

It seems it is possible to handle on either server-side or client-side or maybe both:

- On server-side, we can possibly make sure that unknown fields are ignored. This will have advantage that it will be possible to import new JSON objects in the new format (containing the unknown fields) into the older server. This may be possible with the `@JsonIgnore` annotations on the representation objects.

- On client-side, we can possibly make sure that `null` are not send into JSON. This will have advantage of smaller JSON payloads sent over the network. I am not sure if it is possible.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/32035
- [ ] https://github.com/keycloak/keycloak/issues/32036
```

**Comment by 22liyi** [comment]
强身份验证

**Comment by mposolda** [comment]
Closing as both child issues are fixed and this one is hence fixed as well
