### ISSUE TITLE
Benchmark Identity Providers

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#32229]
### Description

As a follow-up of https://github.com/keycloak/keycloak/issues/31255 we need to run benchmarks to make sure the changes we did so far are enough to scale identity providers in a realm.

This task is about running provisioning data using the `keycloak-benchmark` tool and running test scenarios that stress the following parts of the server:

* Authentication
* Admin API
* Account Console

We need to consider the following numbers when running the benchmark:

* 5k realm-level identity providers 
* 10k organizations with 5 brokers each
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/21261
- [ ] https://github.com/keycloak/keycloak/issues/32573
- [ ] https://github.com/keycloak/keycloak/issues/32574
- [ ] https://github.com/keycloak/keycloak/issues/32575
- [ ] https://github.com/keycloak/keycloak/issues/27053
- [ ] https://github.com/keycloak/keycloak/issues/31256
- [ ] https://github.com/keycloak/keycloak/issues/32233
- [ ] https://github.com/keycloak/keycloak/issues/32091
- [ ] https://github.com/keycloak/keycloak/issues/31944
- [ ] https://github.com/keycloak/keycloak/pull/32497
```

**Comment by cgeorgilakis** [comment]
@sguilhen @pedroigor the most important work for benchmarking Identity Providers are :

-  moving the IDP Mappers to the same provider, decoupling it from the realm.  Take into account that IDP Mappers mappers are more than IDPs. For us around 40000.
- [Identity providers: Pagination in account console (and account REST API)](https://github.com/keycloak/keycloak/issues/21261) based on our discussion there. We can help in it.

Moreover, I have created an [issue for making update IdentityProvider admin REST API more efficient](https://github.com/keycloak/keycloak/issues/32388) and a [related PR](https://github.com/keycloak/keycloak/pull/32391).
Furthermore, you should examine adding to this epic the [SAML/ OIDC IdP AutoUpdate](https://github.com/keycloak/keycloak/issues/11692). Take into account that it is difficult update all these (around 5K) Identity Providers by admin console. I could rebase [my related PR](https://github.com/keycloak/keycloak/pull/8451) once agreed and you could review it.

**Comment by sguilhen** [comment]
> @sguilhen @pedroigor the most important work for benchmarking Identity Providers are :
> 
> * moving the IDP Mappers to the same provider, decoupling it from the realm.  Take into account that IDP Mappers mappers are more than IDPs. For us around 40000.

Yup, this was already addressed as part of https://github.com/keycloak/keycloak/issues/31730.

> * [Identity providers: Pagination in account console (and account REST API)](https://github.com/keycloak/keycloak/issues/21261) based on our discussion there. We can help in it.

Agree with that. As I commented there, I'll get the provider in shape for us to retrieve the IDPs available for linking, then it will be a matter of adding pagination/search params to the endpoint and adjusting the UI as you guys did for a previous version of the console.

> 
> Moreover, I have created an [issue for making update IdentityProvider admin REST API more efficient](https://github.com/keycloak/keycloak/issues/32388) and a [related PR]

@pedroigor This makes sense to me. Do you mind linking this issue in this task to ensure we review/merge it before 26?


(https://github.com/keycloak/keycloak/pull/32391). Furthermore, you should examine adding to this epic the [SAML/ OIDC IdP AutoUpdate](https://github.com/keycloak/keycloak/issues/11692). Take into account that it is difficult update all these (around 5K) Identity Providers by admin console. I could rebase [my related PR](https://github.com/keycloak/keycloak/pull/8451) once agreed and you could review it.

I'd like to have that included before 26 too, let's continue the discussions on that PR.
