### ISSUE TITLE
Failure testing of A/A Architecture

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#32449]
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/924
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/946
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/941
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/944
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/943
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/942
```

**Comment by mhajas** [comment]
All subtasks are finished so closing the epic as well.
