### ISSUE TITLE
Requesting `offline_access` without an established session results in two sessions

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#32650]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

If requesting an offline token using for example a password grant, or for that matter authorization grant when there is no session present results in two sessions; one online and another offline. Especially for the password grant this is unexpected, as the returned tokens are tied to the offline session, and there is no way to revoke the regular session.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

If no regular session exists only an offline session should be created.

### Actual behavior

Two sessions are created.

### How to Reproduce?

* Create a realm with a user, or use any existing realm without sessions for the user
* Add a client that supports direct access grants
* Do a direct access grant request with scope=`offline_access`
* Check in the admin console that there are now two sessions for the user

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/34000
- [ ] https://github.com/keycloak/keycloak/issues/34001
```

**Comment by stianst** [comment]
For a simple reproducer try using https://github.com/stianst/keycloak-tokens-cli/:

```
kct config context create -c test --iss http://localhost:8080/realms/myrealm --client myclient --client-secret secret --flow password --scope offline_access
kct token -d
```

**Comment by mposolda** [comment]
@stianst +1 for the DirectAccessGrant. The "online" session is not needed here.

But for "authorization_code" grant and browser login, I think we need also "online" session in addition to offline session. There is a need to have SSO session in the browser for the subsequent browser logins, which can happen from different applications. This is needed to be tracked with online session. I don't see how we can use only offline session to track browser login as for example idle timeout for SSO session will need to be 30 days (default idle timeout for offline session) instead of 30 minutes, which does not makes sense.

Marking as "important" in order to improve on DirectAccess grant.

**Comment by rmartinc** [comment]
@stianst @mposolda The online session always exists before for the normal browser login, the request should be a code2token to obtain an offline-token, so the session is generated online in the authorization request and it's transformed into offline in the code verification at token endpoint (and the online session remains, that's why there are two now). If we want to delete it at the code step we should add a note at the first auth step (or similar) to know it's the first request for that session and it's requesting offline. WDYT? Do we complicate this to remove the online session for code2token logins?

**Comment by rmartinc** [comment]
I have done a quick test in https://github.com/rmartinc/keycloak/tree/refs/heads/issue-32650-2. And there are several tests that fail. Some of them are OK because they are just counting sessions but, for example, there are a few testing a broker OIDC which is configured to be add offline_access (for example [here](https://github.com/keycloak/keycloak/blob/26.0.0/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/BackchannelLogoutTest.java#L501)). Those tests are very different now as the online session is not created and it's not clear how to change them. My vote is to just remove the session for direct grants and client credentials. But you rule guys :smile:, if you think removing online session for code2token is better I'll try to understand those tests (but maybe they are completely out of date now).

**Comment by mposolda** [comment]
@stianst @rmartinc For the browser login, I still think that we need to keep both online and offline session. Online session is needed for the browser SSO login. So for example scenario like this:

1) Client `client1` sends the login request with `scope=offline_access` . 
2) User needs to authenticate and both online and offline session are created. Note there is SSO cookie `KEYCLOAK_IDENTITY` added
3) Now client `client2` sends the login request (with or without `scope=offline_access`). What happens right now is the automatic SSO login happens because of the online session, which is pointed in the browser in the `KEYCLOAK_IDENTITY` cookie.

If we remove "online" session in the step 2, the automatic SSO login won't happen and user will need to actively login again. I think that is the reason of the broken tests pointed by @rmartinc .

I think that:
- We cannot break the scenario I've pointed above. That would be backwards incompatible change. Also I think that SSO login should just work. The fact that client used `scope=offline_access` in the first request should not be the reason of broken SSO login. The `scope=offline_access` should be additional thing and not have any impact on further SSO re-logins IMO

- We also cannot change SSO login to rely on the offline session. The offline session is dedicated for token refreshes done by the offline client, which could be a long-running background task. But not for SSO browser logins. 

IMO for the browser:
- We can either keep as it is
- We can keep the online user session, but possibly without client session. The online client session is not needed for `client1` as the refreshes will be done with offline token. However we have some logic somewhere to cleanup user sessions if they don't have client sessions. So we need to take some care if we want to change this behaviour

@rmartinc +1 to remove the online session for direct-grants and client-credentials.

**Comment by mposolda** [comment]
@rmartinc Had the chat with @stianst and he is quite convinced we should remove "online" session even for authorization_code grant in case that there was not already online SSO session before. It is fact that it allows some more flexibility and the use-cases, which require purely offline-session don't need to have another possibly redundant "online" session.

However it means the scenario I mentioned in the previous comment TODO is slightly broken. In case that people need SSO session, they will need put additional step with the "online" login, which will create SSO session and then followed with the "offline_access" login.

Is it possible to update existing tests you've mentioned and also make sure that we have the scenarios like those tested:

Scenario 1:

- Login with only `scope=openid`. User should do active authentication (username & password)
- Login with `scope=openid offline_access` . Should do SSO login
- Login with `scope=openid` . Should also do SSO login (as online session exists)

Scenario 2:

- Login with `scope=openid offline_access` . User should do active authentication (username & password)
- Another login with `scope=openid offline_access` . User should do active authentication again (username & password) as online session does not exists.

We will also need to update upgrading guide and make sure that this will be added just to the 26.1.0 as it is a slightly breaking change, so not good for micro-release.

I've created separate subtasks since you already created PR for directGrant+client credentials, so authorization_code could be a follow-up. Does it work for you?

**Comment by mposolda** [comment]
Closing as both subtasks are finished and merged into Keycloak main

**Comment by stefanmaric** [comment]
@mposolda how can a client get an offline session (that's it, a token set that includes a refresh token) but also ensure the user keeps an online session (that's it, authenticated against keycloak via its cookies)?

I guess it can be achieved by sending a authorization request with `openid` only and upon receiving the code/token redirect back to the authorization request with the additional `offline_access` scope. But the additional round trip(s) seems very inefficient and implementation cumbersome as it would have to be done by every client if one wanted to keep the pre-26.1 behaviour, which my clients dearly do. 😄

**Comment by michiproep** [comment]
@mposolda I actually got the same question as @stefanmaric 
If an application needs "openid offline_access", you always need two roundtrips to establish an online session.
From the discussions above I do not really understand the reason.

In our case, we actually provide an enterpise-wide libarary for all our developers which by default requests offline_access.
In this case, we are never able to establish an online session and have seamless SSO in other applications.

Is it possible to get a feature toggle for that behaviour?

**Comment by stefanmaric** [comment]
@michiproep I actually spoke from a place of misunderstanding, maybe it is also your case:

I thought the `offline_access` scope was necessary to get a Refresh Token during the Authorization Flow, but that's actually incorrect. OIDC defines:

> offline_access
        OPTIONAL. This scope value requests that an OAuth 2.0 Refresh Token be issued that can be used to obtain an Access Token that grants access to the End-User's UserInfo Endpoint even when the End-User is not present (not logged in).

And:

>  The use of Refresh Tokens is not exclusive to the offline_access use case. The Authorization Server MAY grant Refresh Tokens in other contexts that are beyond the scope of this specification.

Ref: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

Basically, it is meant for applications that access the Resource Owner's data even when the user is absent, that's it, not using the Client app. Think of integrations like email clients that sync your emails and calendar events in the background while you sleep.

What I actually needed to do is to remove the `offline_access` scope from all my Client's configurations, as none of them actually hit Resource Servers while the user is away. They all still get a refresh token as usual and they all now share the Online Session at Keycloak.

I suspect this common misconception stems from [other](https://auth0.com/docs/secure/tokens/refresh-tokens/get-refresh-tokens), [many](https://developer.okta.com/docs/guides/oie-embedded-common-refresh-tokens/main/#refresh-the-tokens-with-the-oauth-token-endpoint), [popular OAuth providers](https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc#the-offline_access-scope) requiring you to ask for `offline_access` to get Refresh Tokens, even tho not required by any of the OIDC specs and not even mentioned anywhere by the OAuth ones.

I guess it makes sense for organizations like Google or Microsoft giving uncontrolled Clients access to their auth system to assume any refresh token might be used while the user is absent.

All my customers use Keycloak to authenticate only first-party Clients so removing the `offline_access` scope was the ideal solution.

**Comment by michiproep** [comment]
@stefanmaric 
Thanks a lot for this detailed explaination!
You're totatlly right with "..suspect ... from other ..."

In fact, if I do not request ``offline_access`` I still get a refresh token with ``"typ":"Refresh"``
With offline scope, a token of type ``"typ":"Offline"`` is issued.

But this still leaves two open questions:
1. How do those two refresh tokens differ?
2. Let's say an app really needs ``offline_access``, do you still need two roundtrips to the IdP to establish an online session?

**Comment by stefanmaric** [comment]
> 1. How do those two refresh tokens differ?

Basically different expiration behaviours, with different sets of configuration options.

Keycloak's docs talk a bit about it: https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-access

Here the different config options: https://www.keycloak.org/docs/latest/server_admin/index.html#_timeouts


> 2. Let's say an app really needs `offline_access`, do you still need two roundtrips to the IdP to establish an online session?

I'm not qualified to speak on behalf of the project since I'm a simple consumer, but based on my testing, this thread, and other docs, it seems the case.
