### ISSUE TITLE
Downgrade Java for client libraries to 8

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#33050]
We need to support Java 8 for keycloak client libraries.

We will probably need to update keycloak repository as well and make sure that all the modules used for syncing stuff to keycloak-client (`keycloak-common`, `keycloak-core`, `keycloak-admin-client-tests`, `keycloak-authz-client-tests`) are downgraded to Java 8 to avoid introducing any stuff, which cannot be used by the client. It means we will probably need to partially revert this commit https://github.com/keycloak/keycloak/commit/dad4477995de9c4955eab1f5d73d92680e90056d (especially will likely need to re-introduce stuff in keycloak-core for specific versions of classes `JWKBuilder` and `JWKParser` for older Java)

For keycloak-client repository, we will need to downgrade language level here: https://github.com/keycloak/keycloak-client/blob/26.0.0-alpha2/pom.xml#L68-L70 . And we will possibly need to sync the files from keycloak once the changes above are done in keycloak repository. But we can keep testing with GH actions just with Java 17 (at least for now).
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/33051
- [ ] https://github.com/keycloak/keycloak-client/issues/70
- [ ] https://github.com/keycloak/keycloak/issues/33186
```

**Comment by jonkoops** [comment]
Agreed, there is no reason to downgrade the source. Only the target for the compiler should be lowered for compatibility.
