### ISSUE TITLE
Add tooling to ensure protobuf message compatibility between releases

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#33564]
### Description

In order to ensure that protobuf wire compatibility is not broken between Keycloak minor and patch releases, we have agreed to adopt the following procedure:

1. When creating a release branch from `main`, `proto.lock` files must be generated and committed to the release branch
2. Both main and release branches will utilise the `proto-schema-compatibility-maven-plugin` to check their current protobuf definitions against remote `proto.lock` files from older release branches
3. The `main` branch should not contain a `proto.lock` as this will be overly restrictive for feature-development, instead compatibility is ensured by 2.
4. All PRs raised against release branches containing updates to protobuf schemas must also commit proto.lock changes.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/30684
- [ ] https://github.com/keycloak/keycloak/issues/33565
- [ ] https://github.com/keycloak/keycloak/issues/33566
- [ ] https://github.com/keycloak/keycloak/issues/33692
- [ ] https://github.com/keycloak/keycloak/issues/34147
```
