### ISSUE TITLE
Simplify Keycloak node discovery

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#34102]
### Description

A common complaint of users attempting to create Keycloak clusters in non-kubernetes environments, is that it's hard to configure the JGroups discovery protocol that Infinispan relies upon to discover cluster members. This results in users struggling to move from single Keycloak instances to clustered deployments and often requiring additional support. Users often conflate this negative experience with their view of Infinispan, resulting in the project being perceived as a pain point which may prevent users adopting Infinispan for their own projects.

The JGroups project provides a set of JDBC_PING protocols which utilise a DB table to track cluster members leaving/joining. As Keycloak is already reliant on users providing a DB, it's possible for us to automatically configure the discovery protocol to be JDBC_PING2 when a --cache-stack is not explicitly defined. Consequently, the majority of users will no longer need to learn about JGroups discovery protocols in order to establish a Keycloak cluster.

### Discussion

N/A

### Issues

```[tasklist]
### Tasks
- [ ] #29399
- [ ] https://github.com/keycloak/keycloak/issues/34265
- [ ] https://github.com/keycloak/keycloak/issues/34339
- [ ] https://github.com/keycloak/keycloak/issues/34253
- [ ] https://github.com/keycloak/keycloak/issues/34495
- [ ] https://github.com/keycloak/keycloak/issues/34313
- [ ] https://github.com/keycloak/keycloak/issues/34337
```

```[tasklist]
### Future Tasks in other milestones
- [ ] https://github.com/keycloak/keycloak/issues/33651
```

**Comment by thomasdarimont** [comment]
Do you also plan to support to encrypt the JGroups communication with this revised JGroups configuration?

I'm thinking of providing support via flags for:
```xml
...
<SSL_KEY_EXCHANGE keystore_name="/app/certs/vbskc.p12" keystore_password="..." port="7128" stack.combine="INSERT_AFTER" stack.position="VERIFY_SUSPECT2"/>
<ASYM_ENCRYPT asym_keylength="2048" asym_algorithm="RSA" change_key_on_coord_leave = "false" change_key_on_leave = "false" use_external_key_exchange = "true" stack.combine="INSERT_BEFORE" stack.position="pbcast.NAKACK2"/>
```

**Comment by ahus1** [comment]
We are skipping "Consider simplifying or removing CacheBuildSteps as caches are now initialized by the Keycloak Session Factory" as we still use the async initialization to avoid a startup time regression on the UDP stack. Task removed.

**Comment by ahus1** [comment]
@thomasdarimont - please create a new enhancement issue and elaborate on that idea and the problem it solves. Then post the issue number here as a comment.

cc: @ryanemerson

**Comment by thomasdarimont** [comment]
@ahus1 Thanks! I just created this followup issue: https://github.com/keycloak/keycloak/issues/34546

**Comment by ahus1** [comment]
In https://github.com/keycloak/keycloak/pull/34312#issuecomment-2444192959 @stianst asked if the different caching options could be wrapped in features `cache:v1` and `cache:v2`.

> So, guess this is really the okay approach until we have that.

IMHO we don't have it today, so I'm considering this feature now delivered from the SRE team's point of view. Once the CND team with @vmuzikar delivers functionality to support that, we can help to implement that.
