### ISSUE TITLE
Run Keycloak in ROSA clusters on ARM

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34442]
### Description

OpenShift with hosted control planes now supports ARM workers. Using such workers would be in-line with our company "green" strategy, could save costs, and would be a great signal to the community that Keycloak supports ARM. 

### Motivation

Save cloud costs both for us and our users

### Details

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1022
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1027
- [ ] https://github.com/keycloak/keycloak/issues/35775
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1062
- [ ] https://github.com/keycloak/keycloak/issues/34848
- [ ] https://github.com/keycloak/keycloak/issues/34850
```

**Comment by ahus1** [comment]
@kami619 - this issue has been converted to an epic. Please create a new issue (possibly in keycloak-benchmark) for the first 1-2 tasks as a task breakdown. I can then update the task list above with those issues. 
Thanks!

**Comment by ahus1** [comment]
@kami619 - would we skip these two items? There might be no more documentation needed, and not sure if we want to do any Green IT outreach with our results. Please let me know your thoughts.

> Extend the documentation on how run it on ARM

> promote it with the "green IT" community to reach people outside of the Keycloak bubble with a blog post in the Keycloak blog (which then can also be cross-published with the CNCF).

**Comment by kami619** [comment]
I would skip these two items for now and come back to them at a later stage, if we start seeing gains in our AWS costs over a period of time, at least for now, we cannot recommend this for cost savings with confidence.

**Comment by ahus1** [comment]
Closing this epic, as all items are now complete. Thanks!
