### ISSUE TITLE
Metrics that an admin can use for capacity planning of the system

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34503]
### Description

Metrics that an admin can use for capacity planning of the system, especially those we use in the sizing guide (number of password based logins, number token refreshes, number of client credential grants). A growth in those metrics would indicate they would need to increase the resources of Keycloak in-line with actual and anticipated growth. 

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/33043
- [ ] https://github.com/keycloak/keycloak/issues/34602
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1050
- [ ] https://github.com/keycloak/keycloak/issues/35573
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1074
- [ ] https://github.com/keycloak/keycloak/issues/36048
- [ ] #35640
```

```[tasklist]
### Optional
- [ ] Calculator as a stretch goal or a dashboard or ???
- [ ] How to size the internal caches (caches size: realms and users; input: active users within 1 hours + active users groups within an hour + active clients within hour for user login + active clients for client credential grants within an hour)
- [ ] https://github.com/keycloak/keycloak/issues/36266
```

**Comment by ahus1** [comment]
@kami619 - we have the currently marked as optional task: 

> Add metrics that might be missing for password based logins (optional as long as the current events are sufficient)

As we now have proof that the `login` event captures both cookie and password based login, together with the http server metric as a possible replacement for some, is that sufficient, or should we aim higher and add a metric around hashing?

**Comment by daviddelannoy** [comment]
Hi @ahus1 

Thanks for these improvements, it will be very useful for cluster sizing.
Regarding this specific point of `LOGIN` events, I always hesitate a bit **counting all** `LOGIN` events as in a single day we can observe :

- 1 000 000 `LOGIN` events
  - 15 000 password based login
  - rest of `LOGIN` coming from check-sso/silent-check-sso (so mostly cookie-based-login)

Cookie-based logins are quicker since they exit at the first browser flow step and are not as costly compared to password-based logins. Should we really size the cluster by counting all `LOGIN` events especially if  they represent 98,5% of total LOGIN 

A long time ago, we added a custom detail in the `LOGIN` event specifically for password-based logins to filter them. 
Like the `remember_me` is added in LOGIN event details [here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java#L193) we have something like this [here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java#L211)b: 
`context.getEvent().detail(Details.AUTHENTICATION_MODE, "username_password");`

**Comment by ahus1** [comment]
@daviddelannoy - thank you for reaching out. While you were asking this question, @mhajas was working on a password hashing metric here, which will be part of KC 26.1, so I suppose we've now covered this better: https://github.com/keycloak/keycloak/issues/36048 

About the additional detail in the events: This sounds interesting. Please create an enhancement request and a pull request, and mention me / link it here so I can review it. 

BTW, if you are interested to share your Keycloak story with the community, please [complete our survey](http://bit.ly/keycloak-community) so we can understand more about your setup. Thanks!
