### ISSUE TITLE
Metrics that an admin of Keycloak can use for trouble shooting

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34502]
### Description

Metrics that an admin of Keycloak can use for trouble shooting, finding root causes of errors, slowness of the system, and looming problems due to resource shortages for example in connection pools or memory usage.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/35415
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1069
- [x] Troubleshooting guide - possible root causes and which metrics to check // based on the ones we already describe, not necessarily beyond that.
- [ ] https://github.com/keycloak/keycloak/issues/35807
```

**Comment by ahus1** [comment]
Marking "Troubleshooting guide - possible root causes and which metrics to check // based on the ones we already describe, not necessarily beyond that." completed as I see that there is now an example. Change it back to non-completed if you think otherwise.

**Comment by ahus1** [comment]
All tasks completed, epic closed :tada:
