### ISSUE TITLE
Metrics that an admin can use as service level indicators (SLI)

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34501]
### Description

Metrics that an admin can use as service level indicators (SLI) and a base for a Service Level Objectiveas those metrics capture the observed behavior of the system by a user. Those SLIs are usually negotiated with other stakeholders of the system.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/35127
- [ ] https://github.com/keycloak/keycloak/issues/35238
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1057
```
