### ISSUE TITLE
Grafana Dashboards

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34651]
### Description

With an overview of important metrics in place, and a list of service level indicators (SLIs) that describe the behavior as observed by users, the next step is to visualize them on a dashboard to assess the health of an installation.

[Current preview of the dashboard (Grafana JSON Source)](https://github.com/keycloak/keycloak-benchmark/blob/main/provision/minikube/monitoring/dashboards/keycloak-status.json)

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/1031
- [x] Create dashboards to cover #34501
- [x] Create dashboards to cover #34502
- [x] Create dashboards to cover #34503
- [ ] https://github.com/keycloak/keycloak/issues/37129
- [ ] Deliver the dashboards as a preview
```

**Comment by liorkesos** [comment]
Awesome - Looking forward for pseudo official grafana dashboard - all of the good stuff I've seen till now requires an additional exporter - https://github.com/aerogear/keycloak-metrics-spi
It would be awesome to maybe merge this stuff in or to use it as inspiration this seems to be the most popular grafana dashboard https://grafana.com/grafana/dashboards/10441-keycloak-metrics-dashboard/

**Comment by ahus1** [comment]
For those watching this issue, there is a current preview of a dashboard available here: https://github.com/keycloak/keycloak-benchmark/blob/main/provision/minikube/monitoring/dashboards/keycloak-status.json

**Comment by mhajas** [comment]
The documentation for Grafana dashboard is available here: https://www.keycloak.org/nightly/observability/grafana-dashboards (at the moment it is only part of the nightly build, it will be moved to main page with the next release)

JSON definitions for dashboards are available in https://github.com/keycloak/keycloak-grafana-dashboard
