### ISSUE TITLE
Decouple Node.js adapter from Keycloak release cycle

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#34862]
Part of deprecating the Node.js adapter will involve de-coupling it from the main Keycloak project so they are no longer released together.
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/520
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/634
- [ ] https://github.com/keycloak/keycloak/issues/35539
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/551
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/550
- [ ] https://github.com/keycloak/keycloak/issues/35536
- [ ] https://github.com/keycloak/keycloak-web/issues/550
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/558
- [ ] https://github.com/keycloak/keycloak-nodejs-connect/issues/552
- [ ] https://github.com/keycloak/keycloak/issues/36440
- [ ] https://github.com/keycloak/keycloak-web/issues/538
```

**Comment by mposolda** [comment]
Closing the epic as the "core" work was done and node.js adapter is decoupled from Keycloak release cycle. Moving remaining task https://github.com/keycloak/keycloak-web/issues/538 for announcements of keycloak-web out of this epic and handling it as a separate issue.
