### ISSUE TITLE
Make sure keycloak-quickstarts main branch to have released versions of server and client

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#35433]
We had the discussion about quickstarts within the wider team. The approach, which we are going to use is the following:

-    In quickstarts, we won't have anymore branch `latest`. We will have just the branch `main`. This will be also the default branch

- The `main` branch of quickstarts won't have references to snapshot versions of keycloak and keycloak-client. Instead, it will have references to last released version of keycloak server and last released version of keycloak-client. In other words, those lines will be always set to last released version of keycloak server and keycloak-client (Keycloak-client was already updated yesterday by Stian to last released version 26.0.2): https://github.com/keycloak/keycloak-quickstarts/blob/main/pom.xml#L38-L39

- During the release of keycloak server, it will update just this one line in main branch in `pom.xml` with the server version. Similarly for the release of keycloak-client.

- There won't be tags for community quickstarts (looks that nobody using them anyway)

- Sending PRs: The proposal above means that if people are sending PRs to quickstarts, they will need to do quickstart examples which work with the last released version of server and client. So for example if you want to add quickstart for some new feature, which is going to be developed in 26.1.0, it means that this quickstart can be merged to main branch after the Keycloak server 26.1.0 is released. It cannot be merged before though due the server version in pom.xml is pointing to last released version (which is not 26.1.0, but some older like 26.0.X).

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/627
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/639
- [ ] https://github.com/keycloak/keycloak/issues/35437
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/629
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/630
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/631
- [ ] https://github.com/keycloak/keycloak/issues/35439
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/636
```

**Comment by mposolda** [comment]
Closing as all subtasks are finished.
