### ISSUE TITLE
Enhanced Bootstrapping and Recovering Admin Access

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#9829]
# Bootstrapping a temporary admin account

Bootstrapping supports both an admin user account and admin service account. This proposal is describing bootstrapping that is meant as a replacement for the current `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` env vars. It does not replace the admin creation using Welcome Page.

## Temporary admin user and admin service account specifications

* Meant to be only a temporary account that is used for creating permanent and more secure admin access.
* By default expires (is deleted) after 2 hours.
    * This is configurable by the user.
* In case of the user account, clear warning is visible in the Admin Console when logged in as this user.
    * A bar at the top of all Admin Console pages.
* The user/client is cleary marked as temporary in the lists in Admin Console.
* A warning is emitted in the log any time such a user logs in.
* The warnings include a note when the account will be deleted.

In automated scenarios, an admin service account is a more suitable alternative to an admin user.

### Bootstrapping an admin user using a dedicated command

Add a new command: `kc.sh|bat bootstrap-admin user [--username=value] [--password=value] [--no-prompt] [--expiration=value]`.
* The command works regardless if Keycloak was ever started (and master realm exists), or not.
* If `--username` is not specified, the env variable `KEYCLOAK_BOOTSTRAP_ADMIN_USER` will be checked, if it is not defined, the user will be prompted to enter a username with a default preset to `temp-admin`.
* If `--password` is not specified, the environment variable `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD` will be checked, if it is not defined, the user will be prompted for a password.
* If `--no-prompt` is specified, then prompting will not be used. If a value would have required prompting, an error will be shown.
* If the account with the specified username exists an error will be shown.
* `--expiration` specifies the number of minutes after which the account expires. If `--expiration` is not specified, the environment variable `KEYCLOAK_BOOTSTRAP_ADMIN_EXPIRATION` will be checked. Otherwise, the default `120` (2 hours) will be used.

### Bootstrapping an admin user at server startup

* Usable only if Keycloak was not started before, i.e. the master realm doesn't not exist.
* When the server is starting (`kc.sh|bat start|start-dev`) and the condition specified above is met, it will check the `KEYCLOAK_BOOTSTRAP_ADMIN_USER`, `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD` and `KEYCLOAK_BOOTSTRAP_ADMIN_EXPIRATION` env vars. Their meaning and functionality is identical to as when used as the dedicated command.
* `--no-prompt` is implicit, i.e. if `KEYCLOAK_BOOTSTRAP_ADMIN_USER` is set but `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD` is not, an error will be shown.

## Bootstrapping an admin service account

* Identical to bootstraping the admin user as described above with the following exceptions:
    * Instead of "user", "client-id" is used in param and env var names.
    * Instead of "password", "secret" is used in param and env var names.
* Dedicated command: `kc.sh|bat bootstrap-admin service [--client-id=value] [--secret=value] [--no-prompt] [--expiration]`.
* Bootstrapping at server startup is supported too using the `KEYCLOAK_BOOTSTRAP_ADMIN_CLIENT_ID` and `KEYCLOAK_BOOTSTRAP_ADMIN_CLIENT_SECRET` env vars.

Based on the provided arguments, a Client is created in the master Realm with the following specificationss:
* It has all flows disabled.
* The Client requires authentication.
* Service account is enabled.
* The service account has the admin Realm Role assigned.

## Bootstrapping using the Operator

There will be a dedicated field in the Keycloak CR for bootstrapping the admin user account and admin service account. The implementation will leverage the startup env vars, so it will be effective only for the initial bootstrapping of Keycloak.

```
kind: Keycloak
spec:
  bootstrap-admin:
    expiration: 260
    user:
      nameSecret: 
        name: keycloak-admin-secret
        key: username
      passwordSecret:
        name: keycloak-admin-secret
        key: password
    service:
      clientIdSecret: 
        name: keycloak-admin-secret
        key: client-id
      clientSecret:
        name: keycloak-admin-secret
        key: secret

```

* The content of Secrets referenced by `nameSecret` and `passwordSecret` can be provided by the user, or the Operator will populate them with defaults.
* If the Secret or the Key referenced by `nameSecret` don’t exist, the default as described above is used and is written back to the Secret.
* If the Secret or the Key referenced by `passwordSecret` don’t exist, a password is generated and is written back to the Secret.
* The content of Secrets referenced by `clientIdSecret` and `clientSecret` must be provided by the user.

## Recovering the admin access

It is not possible to recover an admin account without already having admin access. It is possible though to create a new admin account using the dedicated command. In case of Operator/container deployments, we will document ssh-ing to the container is necessary.

Realms with increased security (OTP requirement, passwordles, ...) will have to use the admin service account to recover access to the master realm.

---

Originally discussed in https://github.com/keycloak/keycloak/discussions/8549

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/30003
- [ ] https://github.com/keycloak/keycloak/issues/29324
- [ ] https://github.com/keycloak/keycloak/issues/30002
- [ ] https://github.com/keycloak/keycloak/issues/30004
- [ ] https://github.com/keycloak/keycloak/issues/30009
- [ ] https://github.com/keycloak/keycloak/issues/30011
- [ ] https://github.com/keycloak/keycloak/issues/29325
- [ ] https://github.com/keycloak/keycloak/issues/29355
- [ ] https://github.com/keycloak/keycloak/issues/30540
- [ ] https://github.com/keycloak/keycloak/issues/30658
- [ ] https://github.com/keycloak/keycloak/issues/31160
- [ ] https://github.com/keycloak/keycloak/issues/31491
```

```[tasklist]
### Follow-up tasks
- [ ] https://github.com/keycloak/keycloak/issues/30008
- [ ] https://github.com/keycloak/keycloak/issues/30010
```

**Comment by shawkins** [comment]
The expectation is that #29324 could be easier to reach concensus on and therefore something that we could tackle first. However if there is a concensus that a strictly password based mechanism is not desirable, we can just persue #29325

**Comment by vmuzikar** [comment]
Based on some further discussions, created a summarized design proposal. It's focused on UX, implementation details are deliberately omitted at this stage.

## Bootstrapping a temporary admin user account

### Temporary admin user specifications

* Meant to be only a temporary user account that is used for creating permanent and more secure admin access.
* A clear warning is visible in the Admin Console when logged in as this user.
    * A bar at the top visible at all Admin Console pages?
* A warning is emitted in the log any time such a user logs in.
* The warnings include a note to delete the account when no longer needed.


### Bootstrapping using a dedicated command

Add a new command: `kc.sh|bat bootstrap-admin user [--username=value] [--no-prompt]`.
* If `--username` is not specified, the env variable `KEYCLOAK_BOOTSTRAP_ADMIN_USER` will be checked, if it is not defined, the user will be prompted to enter a username.
* If the environment variable `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD` is not specified, the user will be prompted for a password.
* If `--no-prompt` is specified, then prompting will not be used. If a value would have required prompting, an error will be shown.
* If the account with the specified username exists an error will be shown.

#### Bootstrapping a passwordless admin user

The master realm can be configured to use a passwordless auth flow, or to use some sort of 2nd factor authentication. In such a setup, bootstrapping an admin user with password would be useless as that user could not login. To mitigate this, we might consider creating the user without a password and providing a one-time use token that user uses instead of password on a dedicated login page.

Add a new command: `kc.sh|bat bootstrap-admin user --token [--username=value] [--no-prompt]` which generates a JWT token:
* Short lived (5 minutes)
* One time use only
* Signed by master realm key
* Outputted to stdout for user to copy it

Other functionality of the bootstrap-admin command will remain the same as described above with the exception of the password and the associated env var which won’t be prompted/reflected when `--token` flag is present.

The user accesses a dedicated login page meant for one time login:
* Served on management interface
    * Possibly on the main HTTP(S) interface to allow easier access via Ingress in K8s environment.
* Is disabled by default
* Handled by a special auth flow
* Accepts 2 inputs: username and the token that user copy-pasted from the command output


### Bootstrapping at server startup

The functionality largely remains as is with the exception of the env var names.
* At the server startup, it is checked whether there are any users in the master realm.
* If there are no users and `KEYCLOAK_BOOTSTRAP_ADMIN_USER` and `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD` env vars are set, an admin user is created.

The user created this way is also considered a temporary admin user as described above.

### Bootstrapping using the Operator

There will be a dedicated field in the Keycloak CR for bootstrapping the admin user aligned with and backed by the CLI way as described above.


```
kind: Keycloak
spec:
  bootstrap-admin:
    - user:
      nameSecret: 
        name: keycloak-admin-secret
        key: username
      passwordSecret:
        name: keycloak-admin-secret
        key: password
      tokenSecret:
        name: keycloak-admin-secret
        key: token

```

* The content of Secrets referenced by `nameSecret` and `passwordSecret` can be provided by the user, or the Operator will populate them with defaults.
* The content of Secret referenced by `tokenSecret` must be empty and will be populated by the Operator.
* If the Secret or the Key referenced by `nameSecret` don’t exist, it defaults to “admin” and is written back to the Secret.
* If the Secret or the Key referenced by `passwordSecret` don’t exist, a password is generated and is written back to the Secret.
* If the Key referenced by `tokenSecret` exists, the Operator will not override it and set an error on the CR status.
* `passwordSecret` and `tokenSecret` cannot be set at the same time.

### Recovering the temporary admin user

It is not possible to recover an admin account without already having admin access. It is possible though to create a new admin account using the dedicated command or the Operator as described above.


## Bootstrapping an admin service account

In automated scenarios, an admin service account is a more suitable alternative to a (temporary) initial admin user.


### Bootstrapping using a dedicated command

Similar to temporary admin user.

Add a new command: `kc.sh|bat bootstrap-admin service [--client-id=value] [--realm=value] [--no-prompt]`.
* If `--client-id` is not specified, the env variable `KEYCLOAK_BOOTSTRAP_ADMIN_CLIENT_ID` will be checked, if it is not defined, the user will be prompted to enter a Client ID.
* If `--realm` is not specified, the env variable `KEYCLOAK_BOOTSTRAP_ADMIN_REALM` will be checked, if it is not defined, the user will be prompted to enter a Realm name.
* If `--no-prompt` is specified, then prompting will not be used. If a value would have required prompting, an error will be shown.
* If the Client with the specified ID exists an error will be shown.

Successful execution of the command will result in the following:
* A Client is created in the master Realm.
* It has all flows disabled.
* The Client requires authentication.
* Service account is enabled.
* The service account has all realm management roles for a specified Realm assigned.
* The Client Secret is generated and printed on stdout.


#### Considerations

* We might allow users to provide a custom Secret. On the other hand, a generated one would be considered more secure: it’s long by default, different every time the command is run.
* We might consider passing the generated Secret in a different way than just printing it to stdout which might be considered insecure in some cases. On the other hand, the admin service account is meant to be created and Secret consumed by some automation, so stdout might be straightforward and sufficient for it.
* We might allow creating an admin service account at the server startup. But in this case, generating the Secret and printing it to stdout might not be desirable.


### Bootstrapping using the Operator

There will be a dedicated field in the Keycloak CR for bootstrapping the admin service account aligned with and backed by the CLI way as described above.


```
kind: Keycloak
spec:
  bootstrap-admin:
    - service:
      clientIdSecret: 
        name: keycloak-admin-secret
        key: client-id
      clientSecret:
        name: keycloak-admin-secret
        key: secret

```

* The content of Secret referenced by `clientIdSecret` needs to be provided by the user.
* The content of Secret referenced by `clientSecret` needs to be empty and will be populated by the Operator.
* If the Secret or the Key referenced by `clientIdSecret` don’t exist, the Operator sets an error on the CR status.
* If the Key referenced by `clientSecret` exists, the Operator will not override it and set an error on the CR status.

**Comment by GreySpike** [comment]
Initial temporary admin user account

This is of course open to abuse if any of the mechanisms can be used to force another admin user after the system has been loaded with real data.

If the bootstrap admin is generated on start up, with well known credentials, but only if there is no other admin, is there still a requirement for either a dedicated command or Operator?
But also disabling everything _except_ Admin Console until the bootstrap admin is deleted i.e. it is only a bootstrap user which provides the credentials to define the super admin, plus whatever other config users might regard as bootstrap; the last activity is to login as the new super admin to delete the bootstrap admin and enable full service.

I agree that there should be a clear visual indicator that the bootstrap admin is still active, and that a super admin should be created.

Recovery of admin

I'm tempted to say that this should not be implemented as it is a security hole. Except for casual use, I expect that all the data will be injected via scripting or at least files held in a repo and imported, so in the end the entire installation can be deleted and bootstrapped again from the same set of files.

Service Accounts

The flow as described looks good, if I have understood it correctly.

**Comment by vmuzikar** [comment]
@GreySpike Thank you for the input!

> If the bootstrap admin is generated on start up, with well known credentials, but only if there is no other admin, is there still a requirement for either a dedicated command or Operator?

This is for the recovery purposes as creating a new account is more straightforward than actually recovering one.

> But also disabling everything _except_ Admin Console until the bootstrap admin is deleted

That is an interesting idea but would make it difficult to quickly setup and try Keycloak. It'd have to be tied to the prod profile (`kc.sh start`).

> I'm tempted to say that this should not be implemented as it is a security hole.

Not really. With a "physical" access to the Keycloak instance it is possible to e.g. gain the DB creds in any case. Having a proper recovery flow just simplifies it for the user.

**Comment by GreySpike** [comment]
"That is an interesting idea but would make it difficult to quickly setup and try Keycloak. It'd have to be tied to the prod profile (kc.sh start)."  I agree that dev mode doesn't need it, so it would only be enforcing what the current documentation already states - don't use the default admin in prod, which users will unless they are forced to do otherwise.

**Comment by GreySpike** [comment]
I'm tempted to say that this should not be implemented as it is a security hole.

"Not really. With a "physical" access to the Keycloak instance it is possible to e.g. gain the DB creds in any case. Having a proper recovery flow just simplifies it for the user."

Ok, so Keycloak is relying on the security of the underlying OS. That should be obvious to anyone implementing Keycloak in production, but again my experience is that pre-prod tends to be less secure and by default the same config is moved into prod once the functional tests are green. I am just a little paranoid about this as Keycloak provides authentication services.

But given the assumption about OS security, then your proposals are good.

**Comment by vmuzikar** [comment]
Created a final(-ish) design proposal and updated the issue description with it. Feel free to review @keycloak/cloud-native @keycloak/maintainers @keycloak/maintainers-external.

**Comment by vmuzikar** [comment]
Resolving this as all tasks are done now and only follow-ups remain.

**Comment by Barathwaja** [comment]
Hi @vmuzikar , While testing this scenario, I noticed that the `KC_BOOTSTRAP_ADMIN_USER` is being created in the default **master** realm instead of my custom realm. I don't see any `KEYCLOAK_BOOTSTRAP_ADMIN_REALM` or `KC_BOOTSTRAP_ADMIN_REALM` options currently implemented—please correct me if I'm mistaken.

**Comment by shawkins** [comment]
@Barathwaja the bootstrap admin will be created in whatever is designated as the master realm, you may then use that account to create other realm level admins.

**Comment by Barathwaja** [comment]
@shawkins - Correct — but in my scenario, I already have a custom realm with non-admin users and only one main admin user. If I accidentally delete that main admin, I should still be able to create a temporary user and recover/recreate admin user with privileges to it under my custom realm.

**Comment by vmuzikar** [comment]
> is **KEYCLOAK_BOOTSTRAP_ADMIN_EXPIRATION ** still available?

No, it was never really implemented.

> How to delete temporary admin automatically after bootstrapping.

This is not possible at the moment. There's a [tracker](https://github.com/keycloak/keycloak/issues/30008) for it though it's unsure when or whether at all will get this implemented at  this point.

**Comment by atul-agg** [comment]
@vmuzikar **is it possible to bootstrap without temporary admin**? I am including a permanent admin in master realm during startup using config.json file in /keycloak/data/import/ folder.

Keycloak fails to start if I do not include KC_BOOTSTRAP_ADMIN_USERNAME and KC_BOOTSTRAP_ADMIN_PASSWORD in my docker-compose.yml file. Is there any solution for it?

**Comment by shawkins** [comment]
@atul-agg the bootstrap properties are not required. Feel free to create a new issue or disscussion if you are having a problem.

**Comment by Barathwaja** [comment]
> [@shawkins](https://github.com/shawkins) - Correct — but in my scenario, I already have a custom realm with non-admin users and only one main admin user. If I accidentally delete that main admin, I should still be able to create a temporary user and recover/recreate admin user with privileges to it under my custom realm.

@shawkins - Just following up—I'd appreciate it if you could review and let me know if there's a way to create temporary users under my custom realm, which is already set as the default.

**Comment by shawkins** [comment]
> I'd appreciate it if you could review and let me know if there's a way to create temporary users under my custom realm, which is already set as the default.

No, the original response reflects how the bootstrap admin feature functions.
